Translation Delivery
corona-warn-app/cwa-app-ios pull request #1034
Opened 2020-08-11 06:53 UTC by service-tip-git

Translation Delivery

2020-08-11 06:53 UTC, service-tip-git commented
This pull request is for translation delivery. Please review and approve them,  @I534472

2020-08-11 09:19 UTC, PeterBuchholz reviewed
romanian language is missing a placeholder again

2020-08-11 09:19 UTC, PeterBuchholz commented on src/xcode/ENA/ENA/Resources/Localization/ro.lproj/Localizable.strings
> +"Home_Risk_Low_SaveDays_Item_Title" = "În ultimele 14 zile, înregistrarea în jurnal a expunerilor a fost activă timp de %1$u zile.";
This as already corrected in 1.2.0 in stead of the 14 there should be the placeholder %2$u
See: https://github.com/corona-warn-app/cwa-app-ios/pull/1018/files

2020-08-11 13:01 UTC, steins-code commented on src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
> +"Active_Tracing_Interval_Partially_Active" = "Регистрирането на излагания на риск е било активно през %1$u от изминалите 14 дни.";
this change is wrong

2020-08-11 13:02 UTC, steins-code commented on src/xcode/ENA/ENA/Resources/Localization/bg.lproj/Localizable.strings
> +"Home_Risk_Low_SaveDays_Item_Title" = "Регистрирането на излагания на риск е било активно през %1$u от изминалите 14 дни.";
This change is wrong.

2020-08-12 09:40 UTC, steins-code requested changes
please update the commit

2020-08-13 14:14 UTC, service-tip-git commented
This pull request is for translation delivery. Please review and approve them,  @I534472

2020-08-13 15:37 UTC, steins-code commented
> This pull request is for translation delivery. Please review and approve them, @I534472

I resolved the conflicts in another PR #1050  since I cannot commit to this PR

2020-08-13 15:37 UTC, closed without merging