EXPOSUREAPP-2491 Error Code 400 now has a better wording
corona-warn-app/cwa-app-ios pull request #1149
Opened 2020-09-09 07:31 UTC by SwissMountainFrog

## Checklist

* [ ] This PR does not change text that hasn't been signed off with the RKI. Have a look at the pinned issue [440](https://github.com/corona-warn-app/cwa-app-ios/issues)
* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [ ] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) - Pull Requests that are not linked to an issue with you as an assignee will be closed.
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [ ] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)

## Description

2020-09-09 08:13 UTC, marcussc commented
Please add Label and Milestone, thanks!

2020-09-10 14:35 UTC, marcussc requested changes

2020-09-10 14:50 UTC, janetback approved these changes
Texts approved from UA.

2020-09-10 14:56 UTC, marcussc approved these changes

2020-09-10 14:57 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +Danach können Sie einen neuen Test in der App hinzufügen.";
Just fixed the two-lines, replaced with \n ✏️

2020-09-16 13:05 UTC, ArturFriesen approved these changes

2020-09-16 13:30 UTC, merged