Feature/2667 new interoperability risk calculation screen cross country info
corona-warn-app/cwa-app-ios pull request #1206
Opened 2020-09-21 14:15 UTC by SwissMountainFrog

## Description
This pull request covers the interop feature which is part of https://jira.itc.sap.com/browse/EXPOSUREAPP-2667.

The "Risiko-Ermittlung" screen now has an additional cell about EU wide tracing.

![Screenshot](https://user-images.githubusercontent.com/70148649/93777784-7b3ff500-fc25-11ea-8c0c-97a43237916e.png)

2020-09-21 14:53 UTC, janetback approved these changes
UA: Did not see UA-relevant textss

2020-09-21 15:02 UTC, johannesrohwer requested changes
on my device (iPhone 11 pro) the cell title does not break. Please have a quick look if everything is set up properly here! (I just double checked, the label does not resize at all)

2020-09-21 15:15 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Models/Exposure/ENSettingEuTracingViewModel.swift
> +	let title: String
Could be
```suggestion
	let title = AppStrings.ExposureNotificationSetting.euTracingRiskDeterminationTitle
```

2020-09-21 15:15 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Models/Exposure/ENSettingEuTracingViewModel.swift
> +	let countryListLabel: String
Could be:
```suggestion
	let countryListLabel = AppStrings.ExposureNotificationSetting.euTracingAllCountriesTitle
```

2020-09-22 05:05 UTC, janetback reviewed
UA reviewed

2020-09-22 07:26 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/ENSettingEuTracingViewModelTests.swift
> +	}
Good point. I do it in case somebody changes the initializer, so init() is no longer available (empty attributes).

2020-09-22 07:40 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Views/ENSetting/EuTracingTableViewCell.swift
> +	func configure() {
Will take this over...

2020-09-22 07:50 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Models/Exposure/ENSettingEuTracingViewModel.swift
> +	let countryListLabel: String
Thanks. Refactored it this way.

2020-09-22 07:50 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Models/Exposure/ENSettingEuTracingViewModel.swift
> +	let title: String
Thanks. Refactored it this way.

2020-09-22 11:41 UTC, johannesrohwer commented on src/xcode/ENA/ENA/Source/Models/Exposure/__tests__/ENSettingEuTracingViewModelTests.swift
> +	}
still sounds like something that would cause trouble during compile time for me...

2020-09-22 11:42 UTC, johannesrohwer approved these changes
I retested the labels, thank you for your improvements! 🎉

2020-09-22 12:59 UTC, merged