Fix/exposure manager call all completions
corona-warn-app/cwa-app-ios pull request #1356
Opened 2020-10-16 08:30 UTC by ArturFriesen

## Description
This PR fixes the completion callbacks of exposure detection.
When exposure detection is currently running, call completion with an error.

## Link to Jira
[3174](https://jira.itc.sap.com/browse/EXPOSUREAPP-3174)

2020-10-16 13:47 UTC, SwissMountainFrog approved these changes

2020-10-16 14:26 UTC, marcussc requested changes

2020-10-16 14:26 UTC, marcussc commented on src/xcode/ENA/ENA/Source/AppDelegate.swift
> +		Log.info("AppDelegate: Detect exposure.", log: .riskDetection)
<3

2020-10-16 14:26 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
> +	case exposureDetectionIsRunning
```suggestion
	case isAlreadyRunning
```

2020-10-16 14:26 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Workers/Logging.swift
> +	static let riskDetection = OSLog(subsystem: subsystem, category: "riskdetection")
Indentation seems a little off

2020-10-19 07:29 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Models/Exposure/ExposureManager.swift
> +	case exposureDetectionIsRunning
👍 renamed!

2020-10-19 07:29 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/AppDelegate.swift
> +		Log.info("AppDelegate: Detect exposure.", log: .riskDetection)
❤️

2020-10-19 07:30 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Workers/Logging.swift
> +	static let riskDetection = OSLog(subsystem: subsystem, category: "riskdetection")
Looks good on my side 🤷‍♂️

<img width="738" alt="Bildschirmfoto 2020-10-19 um 09 29 11" src="https://user-images.githubusercontent.com/1941000/96414649-b6662180-11ed-11eb-8135-4d640c64ed11.png">

2020-10-19 07:41 UTC, nickguendling approved these changes

2020-10-19 07:47 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Workers/Logging.swift
> +	static let riskDetection = OSLog(subsystem: subsystem, category: "riskdetection")
oh okay :D

2020-10-19 07:48 UTC, marcussc approved these changes

2020-10-19 07:54 UTC, merged