Feature/task 3630 testresult available
corona-warn-app/cwa-app-ios pull request #1561
Opened 2020-11-23 16:36 UTC by KaiTeuber

## Description
Testresults available will show this new screen

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3630

## Screenshot

2020-11-24 10:10 UTC, janetback approved these changes
UA  reviewed

2020-11-24 10:38 UTC, SwissMountainFrog requested changes

2020-11-24 10:38 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmissionTestresultAvailable_Consent_granted" = "Einverständnis\n“Andere warnen” erteilt";
Hi, maybe this is because of the leading linebreak but the leading quotation marks should be at the bottom
`„Andere warnen“`

2020-11-24 10:38 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmissionTestresultAvailable_Consent_not_given" = "Einverständnis\n“Andere warnen” nicht erteilt";
Same here

2020-11-24 10:38 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Scenes/DynamicTableViewController/DynamicTableViewController.swift
> +			Log.error("Missing dynamic header type: \(String(describing: headerFooter))")
Yes, error logs 😄 😄 😄

2020-11-24 10:38 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Scenes/TestresultAvailable/TestresultAvailableViewModel.swift
> +struct TestresultAvailableViewModel {
Throughout the app, I have seen that we use camel case for `TestResult`, so maybe rename the struct to `TestResultAvailableViewModel`, what do you think?

2020-11-24 10:38 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Scenes/TestresultAvailable/__tests__/TestresultAvailableViewModelTest.swift
> +class TestresultAvailableViewModelTest: XCTestCase {
Same here, should it be camel cased `TestResultAvailableViewModelTest`?

2020-11-24 13:29 UTC, SwissMountainFrog approved these changes

2020-11-25 12:17 UTC, marcussc approved these changes

2020-11-25 12:38 UTC, merged