Feature/3718 task submission flow add alerts
corona-warn-app/cwa-app-ios pull request #1589
Opened 2020-11-27 16:38 UTC by KaiTeuber

## Description
If the user try to cancel the submission flow new alerts will get shown

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3718

## Screenshot
![Screen Shot 2020-11-27 at 17 36 51](https://user-images.githubusercontent.com/2675578/100469787-3d54c680-30d7-11eb-9690-b5f691c2ab9c.png)
![Screen Shot 2020-11-27 at 17 37 18](https://user-images.githubusercontent.com/2675578/100469796-404fb700-30d7-11eb-9097-8d21778365e0.png)

2020-11-27 16:44 UTC, marcussc commented on src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
> -        <scene sceneID="Lgw-rw-O6o">
<3 <3 <3 <3

2020-11-29 11:14 UTC, whiskey approved these changes

2020-11-30 08:05 UTC, nickguendling requested changes

2020-11-30 08:05 UTC, nickguendling commented on src/xcode/ENA/ENA/Resources/Storyboards/ExposureSubmission.storyboard
>          <!--Exposure Submission Symptoms Onset View Controller-->
We should also be able to delete this one, right? 😁

2020-11-30 08:05 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +		guard let navigationController = navigationController else {
Could we just use `navigationController?.present`?

2020-11-30 11:11 UTC, nickguendling approved these changes

2020-11-30 12:05 UTC, janetback approved these changes
UA approved

2020-11-30 12:06 UTC, merged