Update privacy-policy.html [EXPOSUREAPP-3512]
corona-warn-app/cwa-app-ios pull request #1639
Opened 2020-12-08 12:28 UTC by janetback

## Description
Adding amendments that I missed to the German privacy policy

2020-12-08 12:28 UTC, janetback commented
Converting to draft as this is work in progress

2020-12-09 07:37 UTC, whiskey approved these changes

2020-12-09 07:50 UTC, tcfos requested changes

2020-12-09 07:50 UTC, tcfos commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
> +			aktuellen Krankheiten, sondern auch zu Krankheitsrisiken einer Person (z.B.
```suggestion
			aktuellen Krankheiten, sondern auch zu Krankheitsrisiken einer Person (z.&nbsp;B.
```

2020-12-09 20:22 UTC, tcfos approved these changes

2020-12-09 20:22 UTC, merged