Fix: Remove the close button from the screen
corona-warn-app/cwa-app-ios pull request #1654
Opened 2020-12-09 13:46 UTC by 30mar

## Description
The close button is not working is the "Warn others" screen.

**UPDATE**: in the comments it was stated that the updated design in figma doesn't have the button so it should be removed from the app as well.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4181

## Screenshot
![IMG_0005](https://user-images.githubusercontent.com/15270737/101637601-44f86180-3a2d-11eb-8a03-32bbc4c3b939.PNG)
![IMG_0006](https://user-images.githubusercontent.com/15270737/101637608-4590f800-3a2d-11eb-8ca0-b4d731df78f0.PNG)

2020-12-09 13:47 UTC, marcussc approved these changes

2020-12-09 13:50 UTC, tcfos approved these changes

2020-12-09 14:00 UTC, KaiTeuber commented
But you still can pull it down to close the screen?

2020-12-09 14:42 UTC, 30mar commented
@KaiTeuber no you have to go back to dismiss by pull-down, but that is the expected behavior right ?

2020-12-09 14:54 UTC, KaiTeuber commented
>  but that is the expected behavior right ?
I don't know. But after the change you still can pull the screen down and viewmodel.dissmis() is called - I think

2020-12-10 12:45 UTC, nickguendling requested changes
There is a hack in `ExposureSubmissionTestResultConsentViewModel` that makes this change also change the text. See line 63-70.

2020-12-10 12:47 UTC, marcussc commented
> There is a hack in `ExposureSubmissionTestResultConsentViewModel` that makes this change also change the text. See line 63-70.

@whiskey Maybe you can help out here? :)

2020-12-10 13:11 UTC, KaiTeuber requested changes

2020-12-10 13:11 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +						self?.showTestResultSubmissionConsentScreen(supportedCountries: supportedCountries, onDismiss: nil)
please keep the line break style
```suggestion
self?.showTestResultSubmissionConsentScreen(
 							supportedCountries: supportedCountries,
 							onDismiss: nil
 						)						self?.showTestResultSubmissionConsentScreen(supportedCountries: supportedCountries, onDismiss: nil)
```

2020-12-10 13:16 UTC, 30mar commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +						self?.showTestResultSubmissionConsentScreen(supportedCountries: supportedCountries, onDismiss: nil)
Ok sure

2020-12-10 13:35 UTC, KaiTeuber approved these changes

2020-12-10 15:44 UTC, nickguendling approved these changes

2020-12-10 16:49 UTC, merged