Fix/4601 log chronological
corona-warn-app/cwa-app-ios pull request #1842
Opened 2021-01-22 14:43 UTC by ArturFriesen

## Description
Adds chronological order to log export.
Adds "All" segment to log ui.

## Link to Jira
[4601](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4601)

![IMG_56DFB7848EFE-1](https://user-images.githubusercontent.com/1941000/105504845-86d12480-5cc8-11eb-88a5-85259dfbbf8c.jpeg)

2021-01-22 15:55 UTC, KaiTeuber requested changes
I like to see all the added private access rights, could you please also add MARKS inside the struct FileLogger to make this change complet.

2021-01-25 08:13 UTC, ArturFriesen commented
> I like to see all the added private access rights, could you please also add MARKS inside the struct FileLogger to make this change complet.

Done

2021-01-25 10:15 UTC, marcussc approved these changes

2021-01-25 10:28 UTC, tcfos approved these changes

2021-01-25 10:44 UTC, pascal-brause approved these changes

2021-01-25 10:44 UTC, KaiTeuber approved these changes

2021-01-25 12:07 UTC, merged