4838 remove zuletzt one day risk
corona-warn-app/cwa-app-ios pull request #1882
Opened 2021-01-29 12:38 UTC by naveeddotio

## Description
If there was only one exposure (high or low risk), the text "Zuletzt am date" is replaced with "Am date "
The green risk card with low risk, shows the date of the last exposure similar to the red risk card
Refactoring risk data model
Adding a new launch argument for number of days with risk exposure
Adding tests and screenshots

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4838
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4839
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4876
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4895

## Screenshots
![Simulator Screen Shot - Clone 1 of iPhone 11 - 2021-01-29 at 13 08 53](https://user-images.githubusercontent.com/77438487/106275943-05811100-6237-11eb-99e3-90d3b2f2476f.png)
![Simulator Screen Shot - Clone 1 of iPhone 11 - 2021-01-29 at 13 10 45](https://user-images.githubusercontent.com/77438487/106275955-0a45c500-6237-11eb-94f5-0089a398cbe3.png)
![Simulator Screen Shot - Clone 1 of iPhone 11 - 2021-01-29 at 13 14 30](https://user-images.githubusercontent.com/77438487/106275973-10d43c80-6237-11eb-82b7-dfd85ed52a95.png)
![Simulator Screen Shot - Clone 1 of iPhone 11 - 2021-01-29 at 13 13 22](https://user-images.githubusercontent.com/77438487/106275984-1598f080-6237-11eb-85d6-a6c1fc6a0222.png)
![Simulator Screen Shot - Clone 1 of iPhone 11 - 2021-01-29 at 13 36 28](https://user-images.githubusercontent.com/77438487/106275998-20538580-6237-11eb-9b12-411f4690c9a7.png)
![Simulator Screen Shot - Clone 1 of iPhone 11 - 2021-01-29 at 13 35 47](https://user-images.githubusercontent.com/77438487/106276046-32352880-6237-11eb-8bde-90cd91ab209f.png)

2021-01-29 13:13 UTC, nickguendling requested changes, later dismissed
Looking good! I think the changes for the detail screen are missing (ExposureDetectionViewController/Model)

2021-01-29 15:45 UTC, naveeddotio commented
> Looking good! I think the changes for the detail screen are missing (ExposureDetectionViewController/Model)

@nickguendling added the changes. Thanks!

2021-02-01 09:19 UTC, SabineLoss approved these changes
UA reviewed

2021-02-01 09:47 UTC, naveeddotio commented
> UA reviewed

Thanks

2021-02-01 09:48 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/__tests__/ExposureDetectionViewModelTests.swift
> +		if hasAtLeastOneDayWithLowRiskLevel == false {
@marcussc thanks for looking, I was going with the wind :D

2021-02-01 13:32 UTC, ArturFriesen approved these changes

2021-02-01 13:32 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
> +			numberOfExposures > 0 ? riskDataSectionWithExposure : riskDataSectionWithOutExposure,
```suggestion
			numberOfExposures > 0 ? riskDataSectionWithExposure : riskDataSectionWithoutExposure,
```

2021-02-01 13:32 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
> +		if let mostRecentDateWithLowRisk = mostRecentDateWithLowRisk {
```suggestion
		if let mostRecentDateWithLowRisk = risk.details.mostRecentDateWithRiskLevel {
```

2021-02-01 14:10 UTC, tcfos approved these changes

2021-02-01 16:11 UTC, merged