Feature/4787 adjust info screen new release features 1.13
corona-warn-app/cwa-app-ios pull request #1929
Opened 2021-02-05 12:11 UTC by SwissMountainFrog

This PR is a refactoring of the delta onboarding so that it now behaves generic. It is possible, to now have multiple delta onboardings for the same version as well as to re-use the same delta onboarding controller for another release (e. g. the new features controller).

It is [based on the JIRA Ticket 4787](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4787)

2021-02-05 12:20 UTC, whiskey commented on src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeltaOnboardingViewController.swift
> +		alert.addAction(UIAlertAction(title: "Ok", style: .cancel))
Not localized?

2021-02-05 12:41 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Developer Menu/Features/DMDeltaOnboardingViewController.swift
> +		alert.addAction(UIAlertAction(title: "Ok", style: .cancel))
We do not localize DM entries, do we?

2021-02-05 17:07 UTC, KaiTeuber requested changes

2021-02-05 17:07 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingProtocols.swift
> +	/// b) can reuse existing prodotocl implementation (e. g. new features) by just changing the version.
```suggestion
	/// b) can reuse existing protocol implementation (e. g. new features) by just changing the version.
```

2021-02-05 17:07 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
> +		static let feature113AddInfoAboutTestProcedureDescription = NSLocalizedString("NewVersionFeature_113_additonal_info_about_test_procedure_description", comment: "")
Localized strings value are on another PR?

2021-02-08 13:39 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/View Helpers/AppStrings.swift
> +		static let feature113AddInfoAboutTestProcedureDescription = NSLocalizedString("NewVersionFeature_113_additonal_info_about_test_procedure_description", comment: "")
Yes, was a separate [PR 1878](https://github.com/corona-warn-app/cwa-app-ios/pull/1878)

2021-02-08 14:07 UTC, KaiTeuber approved these changes

2021-02-08 14:31 UTC, ArturFriesen approved these changes

2021-02-08 14:31 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/Onboarding/DeltaOnboarding/DeltaOnboardingProtocols.swift
> +		if var finishedDeltaOnboardingVersion = store.finishedDeltaOnboardings[version] {
```suggestion
		if var finishedDeltaOnboardings = store.finishedDeltaOnboardings[version] {
```

2021-02-08 15:18 UTC, merged