Fix wrong wording in reset view (EXPOSUREAPP-5017)
corona-warn-app/cwa-app-ios pull request #1937
Opened 2021-02-07 11:54 UTC by Ein-Tim

## Description
This PR changes line 1164 and 1166. "Begegnungs-Aufzeichnungen" is not the term used by Apple in the iOS settings, it's called "Begegnungsaufzeichnungen". (Closes #1934)

## Link to Jira
[EXPOSUREAPP-5017](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5017)

## Screenshots
I'm sadly not (yet) able to provide screenshots, maybe one of the friendly devs could provide one? 😁

2021-02-07 11:57 UTC, dsarkar commented
@Ein-Tim ok, thanks.

2021-02-08 08:57 UTC, tcfos commented
added screenshot

2021-02-08 09:06 UTC, tcfos requested changes
two more:
"RiskLegend_Store_Title" = "Begegnungs-Aufzeichnung";
"RiskLegend_Check_Text" = "Abfrage der Begegnungs-Aufzeichnung und Abgleich mit den Risiko-Mitteilungen anderer Personen. Ihr Risiko wird mehrmals täglich automatisch überprüft.";

2021-02-08 09:16 UTC, janetback requested changes
Hi, Begegnuns-Aufzeichung (i.e. with a hyphen) is the official term as defined in the CWA glossary (I don't know complete history of how this was determined, but presume this comes under 'einfache Sprache#). This should not be changed.

2021-02-08 09:30 UTC, Ein-Tim commented
Mh, okay, @janetback 

This makes no sense to me since the official term from Apple is the one without a hyphen, so I don't understand this desiscion. IMHO this is more likely to lead to confusion than help users, but I accept this. 
I will close this PR but leave the issue #1934 open for further clarification.

Thanks for the feedback.

2021-02-08 09:30 UTC, closed without merging