Feature/4779 texts
corona-warn-app/cwa-app-ios pull request #1950
Opened 2021-02-09 11:42 UTC by 30mar

## Description
Added Survey consent screen and detail screen strings

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4991

## Screenshots
No UI Involved

2021-02-09 13:52 UTC, marcussc approved these changes

2021-02-10 12:33 UTC, tcfos requested changes

2021-02-10 12:33 UTC, tcfos commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"SurveyConsent_Error_AlreadyParticipated" = "Sie haben bereits an der Umfrage teilgenommen. Sie können nur einmal im Monat an der Umfrage teilnehmen (Fehlercode %@).";
```suggestion
"SurveyConsent_Error_TryAgainLater" = "Die Befragung kann aktuell nicht aufgerufen werden. Bitte versuchen Sie es später noch mal (Fehlercode %@).";

"SurveyConsent_Error_DeviceNotSupported" = "Die Befragung kann nicht aufgerufen werden (Fehlercode %@).";

"SurveyConsent_Error_ChangeDeviceTime" = "Die Uhrzeit Ihres Smartphones stimmt nicht mit der aktuellen Zeit überein. Bitte korrigieren Sie die Uhrzeit in den Einstellungen Ihres Smartphones (Fehlercode %@).";

"SurveyConsent_Error_TryAgainNextMonth" = "Die Befragung konnte aus Sicherheitsgründen nicht aufgerufen werden. Sie können im nächsten Kalendermonat wieder teilnehmen (Fehlercode %@).";

"SurveyConsent_Error_AlreadyParticipated" = "Sie haben bereits an der Befragung teilgenommen. Sie können nur einmal im Monat an der Umfrage teilnehmen (Fehlercode %@).";
```

2021-02-10 12:34 UTC, 30mar commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"SurveyConsent_Error_AlreadyParticipated" = "Sie haben bereits an der Umfrage teilgenommen. Sie können nur einmal im Monat an der Umfrage teilnehmen (Fehlercode %@).";
done

2021-02-10 12:42 UTC, tcfos approved these changes

2021-02-10 13:42 UTC, janetback approved these changes
UA reviewed

2021-02-10 16:34 UTC, merged