Feature/task 5099 UI tests
corona-warn-app/cwa-app-ios pull request #2088
Opened 2021-02-25 13:45 UTC by ArturFriesen

## Description
This PR adds UI-Tests for the new contact journal features.

2021-02-25 14:01 UTC, SwissMountainFrog requested changes

2021-02-25 14:01 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
> +		// Select 3th cell.
```suggestion
		// Select 3rd cell.
```

2021-02-25 14:01 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
> +		// Select 3th cell.
```suggestion
		// Select 3rd cell.
```

2021-02-26 12:57 UTC, whiskey requested changes
Kleinkram…

2021-02-26 12:57 UTC, whiskey commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
> +		app.segmentedControls[AccessibilityIdentifiers.ContactDiaryInformation.Day.settingSegmentedControl].firstMatch.buttons.element(boundBy: 1).tap()
Improved readbility:
```suggestion
		let maskSituationButton = app.segmentedControls[AccessibilityIdentifiers.ContactDiaryInformation.Day.maskSituationSegmentedControl].firstMatch.buttons.element(boundBy: 1)
		XCTAssertTrue(maskSituationButton.waitForExistence(timeout: .medium))
		maskSituationButton.tap()

		let settingButton = app.segmentedControls[AccessibilityIdentifiers.ContactDiaryInformation.Day.settingSegmentedControl].firstMatch.buttons.element(boundBy: 1)
 		XCTAssertTrue(settingButton.waitForExistence(timeout: .medium))
		settingButton.tap()
```

2021-02-26 12:57 UTC, whiskey commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
> +		// Select 3th cell.
```suggestion
		// Select 3rd cell.
```

2021-02-26 12:57 UTC, whiskey commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
> +
Something missing here?

2021-02-26 12:57 UTC, whiskey commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
> +		// Select 3th cell.
@SwissMountainFrog DEN hast du übersehen! 🥳

2021-03-01 09:23 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/__tests__/ENAUITests_07_ContactJournalUITests.swift
> +
removed misleading comment.

2021-03-01 09:39 UTC, SwissMountainFrog approved these changes

2021-03-01 09:47 UTC, whiskey approved these changes

2021-03-02 07:10 UTC, tcfos approved these changes

2021-03-02 07:37 UTC, merged