Feature/5590 adjust info screen to announce new release features for 2.0
corona-warn-app/cwa-app-ios pull request #2255
Opened 2021-03-22 10:33 UTC by SwissMountainFrog

PR for the new version feature info screen for version 2.0

![IMG_0514](https://user-images.githubusercontent.com/70148649/111976501-fb2a1780-8b01-11eb-81d7-264927fea3ab.PNG)

[JIRA ticket](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5590)

2021-03-22 10:45 UTC, KaiTeuber approved these changes

2021-03-22 11:23 UTC, ArturFriesen approved these changes

2021-03-22 12:52 UTC, tcfos commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"NewVersionFeature_200_event_checkin_description" = "Die CWA ermöglicht nun einen Check-in für Events und Orte. Personen, die Events veranstalten oder ein Geschäft haben, können über die App einen QR
```suggestion
"NewVersionFeature_200_event_checkin_description" = "Die CWA ermöglicht nun einen Check-in für Events und Orte. Personen, die Events veranstalten oder ein Geschäft haben, können über die App einen QR-Code erstellen. Durch Scannen des QR-Codes können sich Gäste bei Ankunft einchecken, um so ihre Anwesenheit zu registrieren. Auf Wunsch legt die App außerdem einen entsprechenden Tagebuch-Eintrag an. Wird eine eingecheckte Person später positiv auf das Coronavirus getestet, werden alle Personen automatisch gewarnt, die zur selben Zeit eingescheckt waren.";
```

2021-03-22 12:53 UTC, tcfos requested changes
Missing blank in text NewVersionFeature_200_event_checkin_description shall be fixed.

2021-03-25 09:55 UTC, tcfos approved these changes

2021-03-25 09:55 UTC, merged