Feature/6435 rat 3rd party solution integration
corona-warn-app/cwa-app-ios pull request #2464
Opened 2021-04-15 15:46 UTC by KaiTeuber

## Description
Calling the URL https://s.coronawarn.app on the Smartphone opens the CWA and parse the information provided in the QR-Code:
* failure will show an alert
* success will open exposure submission flow and skip internal QR Code scanner

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6464
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6465

## Screenshots
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-15 at 17 42 33](https://user-images.githubusercontent.com/2675578/114898126-227ab880-9e12-11eb-9095-716c23e8cb76.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-15 at 17 42 58](https://user-images.githubusercontent.com/2675578/114898134-24dd1280-9e12-11eb-81ea-1452bd09f457.png)

2021-04-15 16:17 UTC, janetback approved these changes
UA reviewed

2021-04-15 16:18 UTC, BLUM78691 commented
Du sitzt ja immer noch am Rechner …

From: janetback ***@***.***>
Sent: Thursday, 15 April 2021 18:18
To: corona-warn-app/cwa-app-ios ***@***.***>
Cc: Blum, Marion ***@***.***>; Review requested ***@***.***>
Subject: Re: [corona-warn-app/cwa-app-ios] Feature/6435 rat 3rd party solution integration (#2464)


@janetback approved this pull request.

UA reviewed

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/corona-warn-app/cwa-app-ios/pull/2464#pullrequestreview-636879314>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATQ65T4LD455IWYCNESCOHTTI4GS3ANCNFSM427YMZBQ>.

2021-04-15 16:36 UTC, SwissMountainFrog requested changes

2021-04-15 16:36 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/RootCoordinator.swift
> +		// there for we check if the homeCoordinator exists
```suggestion
		// therefor we check if the homeCoordinator exists
```

2021-04-15 16:36 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/RootCoordinator.swift
> +		// there for we check if the homeCoordinator exists
Just a little typo ;-)

2021-04-15 16:36 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +	private func showRATInvalidQrCodeAlert() {
Maybe a bit niggling, but in the localized strings, we do not camelcase `QR`, in the function name `showRATInvalidQrCodeAlert` we mix both. So might `showRATInvalidQRCode` be an option? There are function name examples in our codebase (eg. `.latestQRCodePosterTemplate()`) where we also do not camelCase it. 
Even later down the code road in this file, there is a function `makeQRInfoScreen`.
Just thinking.

2021-04-15 16:41 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> -			onSuccess: { [weak self] testQrCodeInformation in
testQRCodeInformation

2021-04-15 16:46 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
> +			guard let rootViewController = self?.rootViewController,
guard let self = self else { return } to remove too many optional stuff?

2021-04-15 16:47 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
> +	let serverEnvironment: ServerEnvironment
serverEnvironment - spelling mistake here

2021-04-15 16:47 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate.swift
> +		case .checkin(let guid):
checkIn

2021-04-16 08:14 UTC, ArturFriesen requested changes

2021-04-16 08:14 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +					self?.presentedViewController?.dismiss(animated: true) {
Should the success part also be dispatched on main?

2021-04-16 08:14 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +			navigationController?.present(qrScannerNavigationController, animated: true)
Is it Ok, that there can be a call to "self?.showOverrideTestNotice(...)" and after that a call to "navigationController?.present(...)" ?

Seems that there can be 2 navigation calls after each other?

2021-04-16 10:27 UTC, SwissMountainFrog approved these changes

2021-04-16 10:38 UTC, marcussc commented
Labels please :)

2021-04-16 10:46 UTC, BLUM78691 approved these changes
UA approved

2021-04-16 12:23 UTC, ArturFriesen approved these changes

2021-04-16 13:23 UTC, merged