Fix/5941 low risk card title fixes
corona-warn-app/cwa-app-ios pull request #2481
Opened 2021-04-19 12:42 UTC by naveeddotio

## Description
Fixing singular - tag / plural - tagen issue 
Adding heute if daysSinceInstallation is 0

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5941
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5828

## Screenshots
![Simulator Screen Shot - Clone 1 of iPhone 12 - 2021-04-19 at 14 27 36](https://user-images.githubusercontent.com/77438487/115237725-2d3c9280-a11d-11eb-9b37-8161ae99d40d.png)
![Simulator Screen Shot - Clone 1 of iPhone 12 - 2021-04-19 at 14 27 02](https://user-images.githubusercontent.com/77438487/115237737-30378300-a11d-11eb-9bfd-ec972795a913.png)

2021-04-19 13:19 UTC, marcussc requested changes

2021-04-19 13:19 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Risk/HomeRiskCellModel.swift
> +			switch homeState.daysSinceInstallation {
Please don't build logic that is already handled by the OS.
You might want to check out our `Localizable.stringsdict`

2021-04-19 16:29 UTC, janetback approved these changes
UA reviewed.

2021-04-20 09:20 UTC, marcussc approved these changes

2021-04-20 09:53 UTC, merged

2021-04-26 15:34 UTC, janetback reviewed
UA reviewed