extend secure store with test profile
corona-warn-app/cwa-app-ios pull request #2508
Opened 2021-04-21 14:25 UTC by KaiTeuber

## Description
We need to sure the new Test Profil in the App. Added a new model to store the profile, also added some unit tests

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6629

2021-04-21 14:31 UTC, marcussc approved these changes

2021-04-21 14:32 UTC, SwissMountainFrog approved these changes

2021-04-21 14:32 UTC, SwissMountainFrog commented on src/xcode/ENA/ENA/Source/Extensions/ISO8601DateFormatter+extentions.swift
> +	static let justDate: ISO8601DateFormatter = {
Maybe some doc comments about what `justDate` is/should be used for

2021-04-21 14:46 UTC, nickguendling requested changes

2021-04-21 14:46 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Models/Profile/RapidTestProfile.swift
> +		forename: String? = nil,
```suggestion
		firstName: String? = nil,
```
More commonly used and also consistent with TestedPerson on AntigenTest

2021-04-21 14:46 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
> +	var profile: RapidTestProfile? { get set }
```suggestion
	var anitgenTestProfile: RapidTestProfile? { get set }
```

Maybe to make it more clear as there is so much stuff in the store.

2021-04-21 15:27 UTC, nickguendling approved these changes

2021-04-22 08:47 UTC, naveeddotio requested changes

2021-04-22 08:47 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
> +	var anitgenTestProfile: AntigenTestProfile? {
antigenTestProfile

2021-04-22 08:48 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Workers/Store/Store.swift
> +	var anitgenTestProfile: AntigenTestProfile? { get set }
typo here as well

2021-04-22 08:52 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/__tests__/Mocks/MockTestStore.swift
> +	var anitgenTestProfile: AntigenTestProfile?
antigen

2021-04-22 08:52 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Workers/Store/SecureStore.swift
> +	var anitgenTestProfile: AntigenTestProfile? {
done

2021-04-22 08:54 UTC, naveeddotio approved these changes

2021-04-22 09:28 UTC, merged