Feature/6539 adjust info screen to announce new release features for 2.2
corona-warn-app/cwa-app-ios pull request #2532
Opened 2021-04-23 09:32 UTC by SwissMountainFrog

This PR brings the new version features screen for 2.2

JIRA https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6539

![image](https://user-images.githubusercontent.com/70148649/115851639-7b0c1000-a427-11eb-898d-45032fc60711.png)

2021-04-23 09:46 UTC, naveeddotio approved these changes

2021-04-23 13:05 UTC, 30mar approved these changes

2021-04-28 21:35 UTC, KaiTeuber approved these changes

2021-04-29 13:29 UTC, janetback requested changes
UA reviewed

2021-04-29 13:34 UTC, janetback approved these changes
UA reviewed

2021-04-29 14:25 UTC, merged