Fix/4757 accessibility statistics blocks enhancements
corona-warn-app/cwa-app-ios pull request #2535
Opened 2021-04-23 12:24 UTC by SwissMountainFrog

This PR optimized the accessibility experience for the statistics information tiles on the home screen. It combines e.g. the 2 individual lines "Gesamt" and the value "3927" into one single voice-over and therefore reduces the numbers of voice-over "swipes" for the whole statistics tiles.

It also adds additional headline, button, and hyperlink traits to the corresponding elements of the statistic tiles. 

JIRA https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4757

![image](https://user-images.githubusercontent.com/70148649/115870031-f927e100-a43e-11eb-979a-c31bcae1a769.png)

2021-04-23 12:46 UTC, nickguendling requested changes, later dismissed

2021-04-23 12:46 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/HomeStatisticsCardView/HomeStatisticsCardView.swift
> +				}
```suggestion
				}
				tertiaryTitleLabel.accessibilityLabel = tertiaryAccessibilityLabel
```

I guess this also needs to be set in both cases, as you did for the previous two labels

2021-04-26 07:40 UTC, ArturFriesen approved these changes

2021-04-26 16:44 UTC, naveeddotio approved these changes

2021-04-27 20:53 UTC, merged