RAT Create Profile Screen
corona-warn-app/cwa-app-ios pull request #2571
Opened 2021-04-28 11:57 UTC by freshking

## Description

Create RAT Profile Screen with all input fields

## Link to Jira

https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6619

## Screenshots

![IMG_2945](https://user-images.githubusercontent.com/3601228/116399916-b6dd1600-a829-11eb-9bd0-078a5af60838.PNG)

2021-04-28 12:17 UTC, KaiTeuber requested changes

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +		case 0:
can we better use an enum to make thing more readable

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +	private var dateFormatter: DateFormatter!
I think we don't need it. You can use `DateFormatter.localizedString(from: date, dateStyle: .medium, timeStyle: .medium)`  for the default output

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +	}
I think we can be much more simple if you use a KeyPath on the ViewModel, something lie ` func update(_ text: String?, keyPath: WritableKeyPath<DiaryAddAndEditEntryModel, String>)`

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +private class DescriptionCell: UITableViewCell {
please use extra files

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +private class InputCell: UITableViewCell {
separate file?

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +			.sink { [weak self] antigenTestProfile in
why inject the `antigenTestProfile` you could just mure the logic to the viewModel and submit a bool it the input is valid or not ti enable the button

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +	static let identifier = "InputCell"
use the protocol `ReuseIdentifierProviding`?

2021-04-28 12:17 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +	static let identifier = "DescriptionCell"
use `ReuseIdentifierProviding`?

2021-04-28 12:36 UTC, ArturFriesen requested changes

2021-04-28 12:36 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +			if let cell = tableView.cellForRow(at: IndexPath(row: 1, section: 0)) as? InputCell, let currentIndex = cell.textFields.firstIndex(of: textField), (currentIndex + 1) < cell.textFields.count {
Would be nice to have every "let .. =" in a new line.

2021-04-28 12:36 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +		if textField.returnKeyType == .next {
Maybe using guard would reduce the pyramid.

2021-04-28 12:36 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +						!(antigenTestProfile.firstName?.isEmpty ?? true) ||
Would expect the logic for enabling the button in the viewmodel. This way it also can be tested.

2021-04-28 12:36 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +		// self
Comments like that doesn't add any value. Please add more context to the comment. Or remove it. Please also see the other comments.

2021-04-28 12:36 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +		// label
No value comment. Can be removed.

2021-04-28 12:36 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +private class DescriptionCell: UITableViewCell {
Can we have an own file for this cell?

2021-04-28 12:36 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/CreateAntigenTestProfileViewController.swift
> +	static let identifier = "DescriptionCell"
Marks are missing.

2021-04-28 13:19 UTC, KaiTeuber approved these changes

2021-04-28 13:19 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/Cells/CreateAntigenTestProfileDescriptionCell.swift
> +class CreateAntigenTestProfileDescriptionCell: UITableViewCell, ReuseIdentifierProviding {
MARKs

2021-04-28 13:19 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/CreateAntigenTestProfile/Cells/CreateAntigenTestProfileInputCell.swift
> +class CreateAntigenTestProfileInputCell: UITableViewCell, ReuseIdentifierProviding {
MARKs

2021-04-28 21:30 UTC, KaiTeuber requested changes
Please add Unittest for the view models

2021-04-29 07:26 UTC, ArturFriesen approved these changes

2021-04-29 08:58 UTC, KaiTeuber approved these changes

2021-04-29 09:01 UTC, janetback approved these changes
UA reviewed

2021-04-29 09:01 UTC, merged