RAT Profile Localizable Strings
corona-warn-app/cwa-app-ios pull request #2577
Opened 2021-04-28 20:53 UTC by KaiTeuber

## Description
Text added for the antigen-test profile screen

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6618

2021-04-28 21:23 UTC, naveeddotio approved these changes

2021-04-28 21:24 UTC, freshking approved these changes

2021-04-29 04:38 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmission_Antigen_Profile_Information_Image_Description" = "Eine QR Code der eine Person auf dem Smartphone identifiziert.";
German should be "QR-Code" with a hyphen. 
"Eine QR-Code" sounds strange, I would say "Ein QR-Code".

```suggestion
"ExposureSubmission_Antigen_Profile_Information_Image_Description" = "Ein QR-Code der eine Person auf dem Smartphone identifiziert.";
```

@janetback can you confirm?

2021-04-29 04:38 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmission_Antigen_Profile_Information_Description_Title" = "Legen Sie Ihre persönlichen Daten als QR-Code ab, um die Registrierung an der Teststelle  zu beschleunigen.";
I think there is a double whitespace here before "zu beschleunigen" 
```suggestion
"ExposureSubmission_Antigen_Profile_Information_Description_Title" = "Legen Sie Ihre persönlichen Daten als QR-Code ab, um die Registrierung an der Teststelle zu beschleunigen.";
```

2021-04-29 08:28 UTC, janetback commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmission_Antigen_Profile_Information_Image_Description" = "Eine QR Code der eine Person auf dem Smartphone identifiziert.";
Hi @KaiTeuber - I have just provided a screenreader text here for Android - could you please use the same one for iOS? Thanks
"ExposureSubmission_Antigen_Profile_Information_Image_Description" = "Eine Frau mit einem Smartphone in der Hand steht vor einem Gebäude. Ein QR-Code symbolisiert den zu scannenden Schnelltest-Profil.";
```

2021-04-29 08:28 UTC, janetback requested changes
Hi Kai, I have a change request for the screenreader text (see my comment). Thanks.

2021-04-29 08:52 UTC, janetback commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmission_Antigen_Profile_Information_Image_Description" = "Eine QR Code der eine Person auf dem Smartphone identifiziert.";
Hi @Ein-Tim, I have made an alternative text proposal :-) (see my comment)

2021-04-29 08:54 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmission_Antigen_Profile_Information_Image_Description" = "Eine QR Code der eine Person auf dem Smartphone identifiziert.";
Disregard this, @janetback made another proposal [here](https://github.com/corona-warn-app/cwa-app-ios/pull/2577#pullrequestreview-647938787)

2021-04-29 08:58 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmission_Antigen_Profile_Information_Description_Title" = "Legen Sie Ihre persönlichen Daten als QR-Code ab, um die Registrierung an der Teststelle  zu beschleunigen.";
Could you still fix this @KaiTeuber? 

Thanks 🙂

2021-04-29 08:59 UTC, janetback approved these changes
UA reviewed

2021-04-29 12:44 UTC, merged