7595/adapting-privacy-policy-2.4
corona-warn-app/cwa-app-ios pull request #2833
Opened 2021-06-02 11:23 UTC by naveeddotio

## Description
Adapting privacy policy for 2.4

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7597

## Screenshots
NA

2021-06-02 12:10 UTC, SwissMountainFrog approved these changes

2021-06-02 12:46 UTC, marcussc approved these changes

2021-06-02 14:09 UTC, ChristinaTsigganos commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
> +			Die Nutzung der App ist freiwillig. Es ist allein Ihre Entscheidung, ob Sie die App installieren, welche App-Funktionen Sie nutzen und ob Sie Daten mit anderen teilen. Grundsätzlich holen die Haup
please remove the number 19 from "COVID-19-Testzertifikat" and "COVID-19-Impfzertifikat".

2021-06-02 14:50 UTC, ArturFriesen approved these changes

2021-06-02 16:43 UTC, ChristinaTsigganos requested changes
Please adjust the "COVID-19-Testzertifikat" and "COVID-19-Impfzertifikat" by taking out the 19. @naveeddotio

2021-06-07 06:31 UTC, ChristinaTsigganos approved these changes
UA approved

2021-06-07 06:58 UTC, merged