Vaccination certificate: Name determined incorrectly when parts are missing
corona-warn-app/cwa-app-ios pull request #2860
Opened 2021-06-07 14:15 UTC by freshking

## Description

Fix name formatting issues

## Link to Jira

https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7570

2021-06-07 14:21 UTC, ArturFriesen approved these changes

2021-06-07 15:11 UTC, nickguendling requested changes

2021-06-07 15:11 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
> +		return formatter.string(from: nameComponents)
Please check the tech spec: https://github.com/corona-warn-app/cwa-app-tech-spec/blob/ae987cda78e5a21b8caec76f1f878ebeecdfaac9/docs/spec/dgc-overview-client.md#determining-the-display-name-of-the-person-from-a-dgc

2021-06-09 08:17 UTC, freshking commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
> +		return formatter.string(from: nameComponents)
Reverted

2021-06-11 09:42 UTC, mlenkeit commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/Name+Extension.swift
> +		return standardizedGivenName?.components(separatedBy: "<").joined(separator: " ")
if we fall back to the standardized name, we should take it as it is and not replace `<`. There are more adjustments in a standardized name, and with `<`, it's pretty obvious that it's a transliterated name.

2021-06-11 10:17 UTC, nickguendling approved these changes

2021-06-11 12:08 UTC, marcussc approved these changes

2021-06-11 12:08 UTC, merged