Text adjustments legal texts (EXPOSUREAPP-7665)
corona-warn-app/cwa-app-ios pull request #2882
Opened 2021-06-09 13:33 UTC by NataliaLemmerth

2021-06-09 14:29 UTC, ChristinaTsigganos approved these changes
approved

2021-06-09 14:53 UTC, pascal-brause requested changes

2021-06-09 14:53 UTC, pascal-brause commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
> +"ExposureSubmission_TestCertificate_Information_Legal_Text_1" = "Die Anforderung und Verwendung des digitalen COVID-Testzertifikats ist freiwillig. Der Nachweis eines negativen Testzergebnisses kann
```suggestion
"ExposureSubmission_TestCertificate_Information_Legal_Text_1" = "Die Anforderung und Verwendung des digitalen COVID-Testzertifikats ist freiwillig. Der Nachweis eines negativen Testergebnisses kann auch auf andere Weise erbracht werden.";
```

2021-06-09 14:53 UTC, pascal-brause commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
> +"ExposureSubmission_TestCertificate_Information_Legal_Text_1" = "Die Anforderung und Verwendung des digitalen COVID-Testzertifikats ist freiwillig. Der Nachweis eines negativen Testzergebnisses kann
I think there is a "z" too much.

2021-06-09 14:58 UTC, NataliaLemmerth commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.legal.strings
> +"ExposureSubmission_TestCertificate_Information_Legal_Text_1" = "Die Anforderung und Verwendung des digitalen COVID-Testzertifikats ist freiwillig. Der Nachweis eines negativen Testzergebnisses kann
Definitely!

2021-06-09 15:32 UTC, marcussc approved these changes

2021-06-10 08:05 UTC, pascal-brause approved these changes

2021-06-10 08:05 UTC, merged