Fix/7690  At default date to birthday pickers.
corona-warn-app/cwa-app-ios pull request #2895
Opened 2021-06-10 13:27 UTC by ArturFriesen

## Description
At default date to birthday pickers.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7690

2021-06-10 20:40 UTC, pascal-brause approved these changes

2021-06-11 08:09 UTC, marcussc approved these changes

2021-06-11 08:39 UTC, nickguendling requested changes

2021-06-11 08:39 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/AntigenTestProfile/CreateAntigenTestProfile/Cells/CreateAntigenTestProfileInputCell.swift
> +		birthdayPicker.datePickerMode = .date
```suggestion
		birthdayPicker.datePickerMode = .date
		birthdayPicker.maximumDate = Date()
```

2021-06-11 09:06 UTC, nickguendling approved these changes

2021-06-11 09:06 UTC, merged