Feature/7646 certificates detail screens/storybranch
corona-warn-app/cwa-app-ios pull request #2939
Opened 2021-06-15 14:03 UTC by naveeddotio

## Description

For test and vaccination detail screens

1. Design changes
2. Title adjustments
3. Label adjustments and changes
4. Adding stars to gradient
5. Adjusting date formats
6. key value additions
 
## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7756
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7757

## Screenshots

2021-06-15 14:44 UTC, KaiTeuber requested changes

2021-06-15 14:44 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/Checkin/EditCheckInTime/Views/GradientBackgroundView.swift
> +		}
adding the stars in this view will not allow all gradients to use them
As discussed earlier please add the stars to `GradientView` so all other can use it too.
Extend cases with fe `blueWihStars` you can also add the subview with images there.

2021-06-15 15:03 UTC, ChristinaTsigganos approved these changes
UA approved

2021-06-17 11:44 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Cells/HealthCertificateDetailsQRCodeCell.swift
> +		isAccessibilityElement = false
Maybe move all of this to `setupView() `?

2021-06-17 12:37 UTC, KaiTeuber requested changes

2021-06-17 12:37 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Views/GradientView.swift
> +		starImageView = UIImageView(image: image)
we need to make sure UIImageView is nil before set an add it. If it's not nil there might be an old UIImageView, better remove that one from superview before assigning a new one.

2021-06-17 14:04 UTC, KaiTeuber approved these changes

2021-06-17 14:06 UTC, marcussc approved these changes

2021-06-17 14:07 UTC, ArturFriesen approved these changes

2021-06-17 14:16 UTC, merged