feature/7836 FAQ-Link if Certificate is not available
corona-warn-app/cwa-app-ios pull request #2944
Opened 2021-06-15 16:13 UTC by ArturFriesen

## Description
Add handling of labId.
Add faq link to alert.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7836

2021-06-15 16:53 UTC, NataliaLemmerth approved these changes
UA approved

2021-06-16 10:12 UTC, nickguendling requested changes

2021-06-16 10:12 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/TestCertificateRequest.swift
> +		labId = try container.decode(String.self, forKey: .labId)
```suggestion
		labId = try container.decodeIfPresent(String.self, forKey: .labId)
```

Just for downward compatibility, not super important as this class was not released yet, but the developers and testers might appreciate it.

2021-06-16 10:12 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/__test__/HealthCertificateServiceTests.swift
> +		waitForExpectations(timeout: .short)
```suggestion
		waitForExpectations(timeout: .short)
		
		XCTAssertEqual(service.testCertificateRequests.value.first, certificateRequest)
		XCTAssertTrue(certificateRequest.requestExecutionFailed)
		XCTAssertFalse(certificateRequest.isLoading)
```

Would be nice to check that the request is stored and in the failed state

2021-06-16 10:12 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
> +		// If we didn't retrieved a labId for a PRC test result, the lab is not supporting test certificates.
```suggestion
		// If we didn't retrieve a labId for a PRC test result, the lab is not supporting test certificates.
```

2021-06-16 10:38 UTC, freshking approved these changes

2021-06-16 11:36 UTC, nickguendling approved these changes

2021-06-16 12:01 UTC, marcussc approved these changes

2021-06-16 13:06 UTC, merged