Bug/8008 covid test certificate   parts of english translation missing
corona-warn-app/cwa-app-ios pull request #2979
Opened 2021-06-21 13:12 UTC by SwissMountainFrog

This PR adds the missing translations for legal texts in EN and TR
Bug Ticket: https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8008

2021-06-21 13:23 UTC, naveeddotio approved these changes

2021-06-21 14:13 UTC, ArturFriesen approved these changes

2021-06-21 17:37 UTC, Ein-Tim commented
Obsolete with #2981. #2981 merges into `release/2.4.x` which is merged into `release/2.5.x` on a regular basis.

2021-06-22 12:19 UTC, pascal-brause requested changes
When the 2.4 is merged into the 2.5, this would be doubled due to already merged texts with #2981 .
@Ein-Tim is right with his argument.

2021-06-23 08:25 UTC, closed without merging