[Feature] Updated app information - Usage (closes 1123)
corona-warn-app/cwa-app-ios pull request #300
Opened 2020-06-06 20:01 UTC by i336616

Updated Usage content (Nutzung) in App Information

https://jira.itc.sap.com/browse/EXPOSUREAPP-1123

## Checklist

* [x] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [x] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [x] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (if applicable)

2020-06-06 20:12 UTC, thomasaugsten approved these changes

2020-06-07 06:36 UTC, eisvogel requested changes
You somehow submitted an "english" localization file but it is not check in Xcode. You should either remove it or check the box in Xcode. ;-)

<img width="425" alt="image" src="https://user-images.githubusercontent.com/64848654/83962053-f4dfed00-a899-11ea-8ece-9ee4f669989a.png">

2020-06-07 08:48 UTC, i336616 commented
> You somehow submitted an "english" localization file but it is not check in Xcode. You should either remove it or check the box in Xcode. ;-)
> 
> <img alt="image" width="425" src="https://user-images.githubusercontent.com/64848654/83962053-f4dfed00-a899-11ea-8ece-9ee4f669989a.png">

Just updated that now.

2020-06-07 08:49 UTC, eisvogel approved these changes

2020-06-07 08:50 UTC, merged