Correct the Sorting
corona-warn-app/cwa-app-ios pull request #3136
Opened 2021-07-12 15:21 UTC by 30mar

## Description
Incorrect order in Contact Diary for both Locations and Persons for Special characters like: **Ö, Ä, etc**

- Note: We can also modify the sorting inside the database itself but we will need to do a migration, also changing the behavior in the future so i did the sorting in Swift after fetching from the database.

 
## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8177

## Screenshots

![IMG_0117](https://user-images.githubusercontent.com/15270737/125313133-3bbdd300-e335-11eb-9e9c-bf5c2b6dda89.PNG)
![IMG_0118](https://user-images.githubusercontent.com/15270737/125313140-3cef0000-e335-11eb-85b8-e5a0a84080ab.PNG)

2021-07-13 08:03 UTC, pascal-brause reviewed
I would suggest to do the sorting not in the fetching function but in the updateDiaryDays function, because there we do already a map on the raw data. Then we could fusion this to not have manipulations on the raw data in two different functions.

2021-07-13 09:19 UTC, whiskey approved these changes

2021-07-13 10:53 UTC, nickguendling requested changes

2021-07-13 10:53 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/ContactDiary/Store/ContactDiaryStore.swift
> +		})
```suggestion
		let sortedContactPersons = contactPersons.sorted { $0.name.localizedCompare($1.name) == .orderedAscending }
```

I think that's a bit easier to read

2021-07-13 16:04 UTC, KaiTeuber commented
Are you sure the sorting works correctly? In the screenshots Orlando is before Österreich - but Ö is equal to Oe, so it should the opposite order right?

2021-07-14 11:31 UTC, ArturFriesen approved these changes

2021-07-14 12:52 UTC, nickguendling approved these changes

2021-07-14 12:52 UTC, merged