Feature/8504 open test certificate from test result
corona-warn-app/cwa-app-ios pull request #3405
Opened 2021-08-24 13:36 UTC by naveeddotio

## Description
Functionality to open test certificate directly from test result screen

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8504

## Screenshots

2021-08-24 15:23 UTC, nickguendling requested changes

2021-08-24 15:23 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +							}
I think it makes sense to always pop back to the test result on deletion. And probably not back to root, as there could be other view controllers on the stack still.

```suggestion
							self.navigationController?.popViewController(animated: true)
```

2021-08-24 15:23 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
> +	}
I think if you just need it here you can just actually use a tuple. And we don't need the `get` prefix in Swift 😉

```suggestion
	func healthCertificateTuple(for uniqueCertificateIdentifier: String) -> (certificate: HealthCertificate, certifiedPerson: HealthCertifiedPerson)? {
		var healthTuple: (certificate: HealthCertificate, certifiedPerson: HealthCertifiedPerson)?
		self.healthCertificateService.healthCertifiedPersons.value.forEach { healthCertifiedPerson in
			healthCertifiedPerson.healthCertificates.forEach { healthCertificate in
				if healthCertificate.uniqueCertificateIdentifier == uniqueCertificateIdentifier {
					healthTuple = (certificate: healthCertificate, certifiedPerson: healthCertifiedPerson)
				}
			}
		}
		return healthTuple
	}
```

2021-08-25 07:12 UTC, pascal-brause requested changes
I see an dependency to the pdf export story, because the flows would differ now.
See https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8384 for more details. 
Perhaps we have to use the changed UI in the certificate details also here.

2021-08-25 07:57 UTC, pascal-brause approved these changes

2021-08-25 11:49 UTC, nickguendling approved these changes

2021-08-25 11:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
> +
Whoops, whats that? 😆

2021-08-25 11:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/CoronaTestService/CoronaTestService.swift
> +
Should be moved to the private section

2021-08-25 11:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
> +		onTestCertificateTapped: @escaping(HealthCertificate, HealthCertifiedPerson) -> Void
Just realized, would be more in line with the others if named like this

```suggestion
		onTestCertificateCellTap: @escaping(HealthCertificate, HealthCertifiedPerson) -> Void
```

2021-08-25 11:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
> +		self.onTestCertificateTapped = onTestCertificateTapped
```suggestion
		self.onTestCertificateCellTap = onTestCertificateCellTap
```

2021-08-25 11:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
> +	private let onTestCertificateTapped: (HealthCertificate, HealthCertifiedPerson) -> Void
```suggestion
	private let onTestCertificateCellTap: (HealthCertificate, HealthCertifiedPerson) -> Void
```

2021-08-25 11:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/ExposureSubmissionTestResultViewModel.swift
> +					self.onTestCertificateTapped(healthTuple.certificate, healthTuple.certifiedPerson)
```suggestion
					self.onTestCertificateCellTap(healthTuple.certificate, healthTuple.certifiedPerson)
```

2021-08-25 11:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertificate/HealthCertificateViewController.swift
> +
```suggestion
```

2021-08-25 12:55 UTC, merged