Feature/9130 add indicator persons screen
corona-warn-app/cwa-app-ios pull request #3449
Opened 2021-08-31 12:49 UTC by naveeddotio

## Description
Adding an arrow on persons screen that shows regarding a possible navigation

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9130

## Screenshots
![WhatsApp Image 2021-08-31 at 14 48 32](https://user-images.githubusercontent.com/77438487/131505357-3872ca74-0cc6-4c60-8642-2b3ab00d7360.jpeg)
![WhatsApp Image 2021-08-31 at 14 48 27](https://user-images.githubusercontent.com/77438487/131505374-ec0f9ba5-a4f8-4ecc-bc7d-3ceef474f74d.jpeg)

2021-08-31 14:49 UTC, nickguendling requested changes

2021-08-31 14:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonCellModel.swift
> +	let accessoryIcon: UIImage
I would say it's not really necessary to have this in the view model as it always stays the same image. Doesn't need to be configured depending on the certificate for example. (The same could be said about the `title` property as well, doesn't need to be configured or tested either.)

2021-08-31 14:49 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/HealthCertifiedPerson/HealthCertifiedPersonTableViewCell.swift
> +				accessoryIconView.trailingAnchor.constraint(equalTo: gradientView.trailingAnchor, constant: -18.0),
We need a constraint between the `stackView.trailingAnchor` and the `accessoryIconView.leadingAnchor` as well so they don't overlap on bigger font sizes/smaller screen sizes.

2021-08-31 15:39 UTC, nickguendling approved these changes

2021-09-01 07:30 UTC, marcussc approved these changes

2021-09-01 07:30 UTC, merged