change notification text for certificates
corona-warn-app/cwa-app-ios pull request #3619
Opened 2021-10-01 05:06 UTC by 30mar

## Description
change notification text for certificates

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9678

2021-10-01 06:55 UTC, pascal-brause approved these changes

2021-10-01 09:58 UTC, ArturFriesen approved these changes

2021-10-01 10:05 UTC, naveeddotio approved these changes

2021-10-01 10:48 UTC, nickguendling requested changes

2021-10-01 10:48 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
> +		content.body = AppStrings.LocalNotifications.invalidCertificateBody
I think the story is a bit unclear here, but the text should also be changed back for soon expiring and expired certificates.

2021-10-04 14:01 UTC, nickguendling approved these changes

2021-10-05 09:31 UTC, CV113 approved these changes
UA approved

2021-10-05 09:43 UTC, merged