Fix 9750: remove unused empty space at bottom of footer view
corona-warn-app/cwa-app-ios pull request #3628
Opened 2021-10-02 17:30 UTC by ndegendogo

## Description

This PR fixes a layout issue that was reported as #3332 and as #3408.
When the buttons in the footer view were hidden, there was still a constraint setup for the safe area. This appears as unused empty space at the bottom of the view. 

## Link to Jira

Jira:
Internal Tracking-ID: EXPOSUREAPP-9083
Internal Tracking ID: EXPOSUREAPP-9750
github: #3332 and #3408

## Screenshots

2021-10-06 11:17 UTC, marcussc requested changes

2021-10-07 21:10 UTC, ndegendogo commented on src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewController.swift
> +		buttonsStackViewTopConstraint = buttonsStackView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: viewModel.topBottomInset)
@marcussc thanks for the suggestion. It simplifies the solution a lot :-)

2021-10-08 06:56 UTC, pascal-brause commented on src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
> +		}
```suggestion
		updateInsets()
```

2021-10-08 06:56 UTC, pascal-brause commented on src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
> +		}
Should this work, too? Instead of having the code check twice?

2021-10-08 06:56 UTC, pascal-brause commented on src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
> +		updateInsets()
Perhaps you could investigate when `update(to state: VisibleButtons)` is called. When it is called at initialization, perhaps we could spare also the call you created in the initializer. Just an idea, not sure about it.

2021-10-11 10:11 UTC, pascal-brause commented on src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
> +		}
Seems quite better, cool!

2021-10-11 10:11 UTC, pascal-brause approved these changes

2021-10-11 12:04 UTC, marcussc approved these changes

2021-10-11 12:20 UTC, merged