Fix/9667 cancelation button doesnt work in event checkin
corona-warn-app/cwa-app-ios pull request #3637
Opened 2021-10-04 10:25 UTC by 30mar

## Description
Fix the close button by using a navigation bar

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9667

2021-10-04 10:36 UTC, KaiTeuber requested changes

2021-10-04 10:36 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.swift
> +//	@IBOutlet private weak var barGradientView: UIView!
removed please

2021-10-04 10:39 UTC, KaiTeuber commented
This looks broken to me, navigation controller is nil and DismissHandling won't get called:
![Screen Shot 2021-10-04 at 12 38 10](https://user-images.githubusercontent.com/2675578/135837366-ff139fb7-6abe-4d0b-88e1-3b91ce729633.png)

2021-10-04 12:41 UTC, KaiTeuber requested changes

2021-10-04 12:41 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/Events/Checkin/TraceLocationCheckin/TraceLocationCheckinViewController.swift
> +		navigationController?.view.backgroundColor = .clear
This is only needed if you use a normal UINavigationController, but if you do so, the DismissHandling protocol might not work correctly.

2021-10-04 13:35 UTC, KaiTeuber approved these changes

2021-10-05 09:16 UTC, naveeddotio approved these changes

2021-10-05 10:26 UTC, merged