Feature/9802 recycle corona test/10131 recycle tests
corona-warn-app/cwa-app-ios pull request #3753
Opened 2021-10-27 10:12 UTC by nickguendling

## Description
Moves corona tests in and out of the recycling bin.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10131

2021-10-27 10:28 UTC, KathrinLuecke requested changes
Please replace Zertifikat by Testergebnis.

2021-10-29 07:45 UTC, ArturFriesen approved these changes

2021-10-29 13:32 UTC, marcussc approved these changes
`recycleBin: .fake()` 😅

2021-10-29 21:03 UTC, naveeddotio approved these changes

2021-11-01 07:55 UTC, merged