Feature/10349 crypto functions part1/10435 rsa oaep with sha256
corona-warn-app/cwa-app-ios pull request #3829
Opened 2021-11-10 14:40 UTC by KaiTeuber

## Description
Added RSA OAEP with SHA256 to ENASecurity incl. recommended tests

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10435

2021-11-10 14:45 UTC, marcussc commented on src/xcode/ENA/ENASecurity/Sources/ENASecurity/RSAEncryption.swift
> +    private var publicSecKey: SecKey? {
Why not init this struct with the `SecKey` directly? Would remove the optionals. 
An other Idea would be to have an failable init with `Data` that fails if `SecKey` can't be generated from `Data`

2021-11-10 15:29 UTC, ArturFriesen requested changes

2021-11-10 15:29 UTC, ArturFriesen commented on src/xcode/ENA/ENASecurity/Sources/ENASecurity/RSAEncryption.swift
> +import CryptoSwift
Is this import needed?

2021-11-10 15:29 UTC, ArturFriesen commented on src/xcode/ENA/ENASecurity/Sources/ENASecurity/RSAEncryption.swift
> +        guard SecKeyIsAlgorithmSupported(publicKey, .encrypt, SecKeyAlgorithm.rsaEncryptionOAEPSHA256) else {
```suggestion
        guard SecKeyIsAlgorithmSupported(publicKey, .decrypt, SecKeyAlgorithm.rsaEncryptionOAEPSHA256) else {
```

2021-11-10 15:29 UTC, ArturFriesen commented on src/xcode/ENA/ENASecurity/Sources/ENASecurity/RSAEncryption.swift
> +        guard let decodedData = SecKeyCreateDecryptedData(
The guard is a little bit hard to read. I would prefer to have the call of `SecKeyCreateDecryptedData` separated, if possible.

2021-11-11 08:07 UTC, ArturFriesen approved these changes

2021-11-11 09:08 UTC, marcussc approved these changes

2021-11-11 09:11 UTC, merged