feature/5624 add preview for 3 links
corona-warn-app/cwa-app-ios pull request #3898
Opened 2021-11-27 10:35 UTC by ndegendogo

## Description

This PR implements preview for the three following links:
- Statistics info, FAQ (AppStrings.Statistics.Info.faqLink)
- Error reports, FAQ (AppStrings.ErrorReport.faqURL)
- Info for risk card with low-risk encounters, FAQ (AppStrings.Home.riskEncounterLowFAQLink)
This feature was requested at #2179.

## Link to Jira

Jira: Internal Tracking ID: EXPOSUREAPP-5624
github: #2179

## Screenshots

![Simulator Screen Shot - iPhone 8 - 2021-11-27 at 11 14 38](https://user-images.githubusercontent.com/6118267/143677587-4a6fb3a8-731c-4a2f-9311-2bb013380363.png)

![Simulator Screen Shot - iPhone 8 - 2021-11-27 at 11 14 56](https://user-images.githubusercontent.com/6118267/143677599-9192ef4a-915b-45b1-82e9-6b72b1ae1cbf.png)

![Simulator Screen Shot - iPhone 8 - 2021-11-27 at 11 15 33](https://user-images.githubusercontent.com/6118267/143677611-cfc81e38-d347-487b-9859-c2095c693f28.png)

![Simulator Screen Shot - iPhone 8 - 2021-11-27 at 11 15 42](https://user-images.githubusercontent.com/6118267/143677630-c8139a26-133c-4b53-8ba0-781f2fb77842.png)

![Simulator Screen Shot - iPhone 8 - 2021-11-27 at 11 16 37](https://user-images.githubusercontent.com/6118267/143677647-7d31d06e-bbd2-4e7f-88ce-955ad59d9b95.png)

![Simulator Screen Shot - iPhone 8 - 2021-11-27 at 11 16 47](https://user-images.githubusercontent.com/6118267/143677669-82f3b3a9-fd33-4089-83cc-803341f4c403.png)

2021-11-29 08:38 UTC, marcussc requested changes

2021-11-29 08:38 UTC, marcussc commented on src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift
> -		if numberOfExposures > 0 {
Why does this get removed? Seems much needed?

2021-11-29 15:08 UTC, pascal-brause reviewed
Same question like @marcussc: Removing the check for `numberOfExposures > 0` changes the logic. Why removing it?

2021-11-29 22:00 UTC, ndegendogo commented
@marcussc @pascal-brause 
Well ... actually I was looking for an execution path to that code, because I wanted to test the behaviour of the link ... 
but I couldn't find one; so I concluded that it is dead code (maybe forgotten to cleanup after a refactoring ... ).
But of course, I may be wrong.
And even if not: if you want to keep this code, e.g. for future use, I don't insist to delete it, I can bring it back.

*Still I would like to understand it ... I still don't see the execution path ...*
*There are two functions `explanationSection(...)` in this class, and both functions are private - so we can limit our analysis to this class, right?*
*[This one](https://github.com/corona-warn-app/cwa-app-ios/blob/6efafb8b22d78db8abb6b4fd5fecef695717703c/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L610) is called [from the inactiveModel](https://github.com/corona-warn-app/cwa-app-ios/blob/6efafb8b22d78db8abb6b4fd5fecef695717703c/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L340) and [from the failureModel](https://github.com/corona-warn-app/cwa-app-ios/blob/6efafb8b22d78db8abb6b4fd5fecef695717703c/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L358) and both don't have a parameter `numberOfExposures`, so they get the default value -1 and don't hit that condition.*
*The [lowRiskModel](https://github.com/corona-warn-app/cwa-app-ios/blob/6efafb8b22d78db8abb6b4fd5fecef695717703c/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L408) has such a parameter, but it calls [the other function](https://github.com/corona-warn-app/cwa-app-ios/blob/6efafb8b22d78db8abb6b4fd5fecef695717703c/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L636).*
*And the highRiskModel calls a separate function [highRiskExplanationSection](https://github.com/corona-warn-app/cwa-app-ios/blob/6efafb8b22d78db8abb6b4fd5fecef695717703c/src/xcode/ENA/ENA/Source/Scenes/ExposureDetection/ExposureDetectionViewModel.swift#L460).*

2021-11-30 13:30 UTC, marcussc approved these changes

2021-11-30 13:32 UTC, pascal-brause approved these changes
After having a small pair-review with @marcussc, we agree 100% to your solution. We tried a little bit around and came to the same opinion like you.
Nice finding and thanks for your contribution. 🎉

2021-11-30 13:50 UTC, merged