Feature/10879 dm disable allow list validation
corona-warn-app/cwa-app-ios pull request #3931
Opened 2021-12-03 15:30 UTC by KaiTeuber

## Description
Added a DM toggle to skip allow list check

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10879

## Screenshots
![IMG_07F34270B2F1-1](https://user-images.githubusercontent.com/2675578/144628352-c66afd66-083d-4b4e-a241-c601a4c1cf18.jpeg)

2021-12-03 15:45 UTC, 30mar requested changes

2021-12-03 15:45 UTC, 30mar commented on src/xcode/ENA/ENA/Source/Services/TicketValidation/AllowList/AllowListService.swift
> +		}
```suggestion
		if store.skipAllowlistValidation {
			Log.info("Skip allow list toggle in Developer Menu is on", log: .ticketValidation)
			return .success(())
		}
```

2021-12-03 15:45 UTC, 30mar commented on src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/AllowListEvaluationTrust.swift
> +
```suggestion
```

2021-12-03 15:45 UTC, 30mar commented on src/xcode/ENA/ENA/Source/HTTPClient/Security/EvaluateTrust/AllowListEvaluationTrust.swift
> +
```suggestion
```

2021-12-03 15:56 UTC, 30mar approved these changes

2021-12-03 16:29 UTC, 30mar approved these changes

2021-12-06 09:36 UTC, pascal-brause approved these changes

2021-12-06 11:33 UTC, merged