improved numberformatters to correct rounding
corona-warn-app/cwa-app-ios pull request #3933
Opened 2021-12-03 16:21 UTC by KaiTeuber

## Description
Wrong rounded values fixed in the statistic tiles.
Improved NumberFormatters a bit and added a new unit test for that special case.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10616

2021-12-03 18:38 UTC, naveeddotio approved these changes

2021-12-06 09:08 UTC, marcussc approved these changes

2021-12-06 09:08 UTC, nickguendling requested changes

2021-12-06 09:08 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/Home/Cells/Statistics/Extensions/SAP_Internal_Stats_KeyFigure+Formatting.swift
>  		numberFormatter.maximumFractionDigits = Int(decimals)
Moving this number formatter to a static let makes it not thread safe anymore if multiple KeyFigures are asked for their `formattedValue` in parallel, as the same shared object is reconfigured now. Unlikely that there are any practical implications here, but I want to mention it.

2021-12-06 11:33 UTC, nickguendling approved these changes

2021-12-06 23:58 UTC, merged