change to aspect fill
corona-warn-app/cwa-app-ios pull request #4029
Opened 2022-01-02 23:47 UTC by 30mar

## Description
change fill mode to aspect fill

## Link to Jira
(https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8482)

2022-01-03 13:54 UTC, pascal-brause requested changes
I am not sure if changing the contentMode fixes the problem for all device sizes. Because perhaps the image could be stretched on smaller devices. Did you test it on iPhone SE and iPhone Pro Max?
We had a very similar problem, Kai resolved it by another way. Have a look here: https://github.com/corona-warn-app/cwa-app-ios/pull/4008/files

2022-01-03 14:29 UTC, ArturFriesen approved these changes

2022-01-04 03:59 UTC, 30mar commented
@pascal-brause  I tested on xr and iPhone 13 pro max and they look ok
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-01-04 at 04 58 47](https://user-images.githubusercontent.com/15270737/148007809-4e2faf40-41f7-4d98-b6a5-02bec9e3f519.png)

2022-01-04 09:24 UTC, pascal-brause approved these changes
Okay nice!

2022-01-04 09:24 UTC, merged