Add cbor access to CCLConfiguration.
corona-warn-app/cwa-app-ios pull request #4133
Opened 2022-01-26 16:19 UTC by ArturFriesen

## Description
API to access the CCLConfiguration through CBOR.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11473

2022-01-27 07:38 UTC, pascal-brause approved these changes

2022-01-27 15:39 UTC, pascal-brause requested changes

2022-01-27 15:41 UTC, pascal-brause requested changes
The `CCLConfiguration` must be declared public in the Toolkit, too.

2022-01-27 15:41 UTC, pascal-brause commented on src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfigurationAccess.swift
> +enum CCLConfigurationAccessError: Error {
must be public to access it

2022-01-27 16:04 UTC, ArturFriesen commented on src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfigurationAccess.swift
> +enum CCLConfigurationAccessError: Error {
Done

2022-01-28 07:29 UTC, pascal-brause approved these changes

2022-01-28 08:34 UTC, nickguendling commented on src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfigurationAccess.swift
> +    case JSON_ENCODING_FAILED(Error?)
Looks like this not used

2022-01-28 09:19 UTC, ArturFriesen commented on src/xcode/ENA/HealthCertificateToolkit/Sources/HealthCertificateToolkit/CommonCovidLogic/CCLConfigurationAccess.swift
> +    case JSON_ENCODING_FAILED(Error?)
removed

2022-01-28 09:38 UTC, nickguendling approved these changes

2022-01-28 10:02 UTC, merged