Word "Uhr" missing in recycle bin note
corona-warn-app/cwa-app-ios pull request #4154
Opened 2022-02-01 09:22 UTC by CV113

in German language "Uhr" is missing after the time of date

--> https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11636

2022-02-01 09:31 UTC, marcussc approved these changes

2022-02-01 09:39 UTC, KathrinLuecke approved these changes
UA approved

2022-02-01 09:45 UTC, naveeddotio commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"RecycleBin_expirationDateTime" = "wird am %@ um %@ Uhr endgültig gelöscht";
We don't add Uhr in our dates on iOS. We need to be consistent with the format. If we decide we are doing it then we need to do it everywhere.

2022-02-01 09:45 UTC, naveeddotio requested changes
We don't add Uhr in our dates on iOS. We need to be consistent with the format. If we decide we are doing it then we need to do it everywhere.

2022-02-01 13:32 UTC, nickguendling requested changes

2022-02-01 13:33 UTC, nickguendling commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"RecycleBin_expirationDateTime" = "wird am %@ um %@ Uhr endgültig gelöscht";
If we remove it from "Checkin_Details_EventNotStartedYet" as well then we consistently write times without "Uhr" throughout the whole app

2022-02-01 19:14 UTC, naveeddotio commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"RecycleBin_expirationDateTime" = "wird am %@ um %@ Uhr endgültig gelöscht";
I think we should better remove "Uhr" from Checkin_Details_EventNotStartedYet then.

2022-02-03 13:26 UTC, marcussc commented
Closing after chat with UA, UX and Dev.

2022-02-03 13:26 UTC, closed without merging