set the badge if the risk level changes regardless of the level
corona-warn-app/cwa-app-ios pull request #4160
Opened 2022-02-01 14:53 UTC by 30mar

## Description
set the badge if the risk level changes regardless of the level

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11545

2022-02-01 14:58 UTC, KaiTeuber approved these changes

2022-02-01 15:00 UTC, nickguendling requested changes
I think we should reflect the change in behaviour in the name and comment

2022-02-01 15:00 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/Home/HomeCoordinator.swift
>  				self?.badgeWrapper.update(.riskStateIncreased, value: 1)
```suggestion
				self?.badgeWrapper.update(.riskStateChanged, value: 1)
```

2022-02-02 08:52 UTC, nickguendling approved these changes

2022-02-03 10:50 UTC, merged