Feature/11702 configuration is updated all the time
corona-warn-app/cwa-app-ios pull request #4177
Opened 2022-02-04 16:32 UTC by KaiTeuber

## Description
CCLService can detect now if data came from cache or is default and won't indicate and update
Added missing unittests for CCLService

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11702

2022-02-04 16:54 UTC, marcussc approved these changes

2022-02-07 09:01 UTC, naveeddotio approved these changes

2022-02-07 09:02 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/HTTPClientCore/Service/Services/_Service+Default.swift
> +			Log.info("Found a defaultModel wich conforms to MetaDataProviding. Adding metadata now.", log: .client)
```suggestion
			Log.info("Found a defaultModel which conforms to MetaDataProviding. Adding metadata now.", log: .client)
```

2022-02-07 09:03 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/CCLConfiguationTests.swift
> +	// MARk: - Configuration logic on CCLService Layer
```suggestion
	// MARK: - Configuration logic on CCLService Layer
```

2022-02-07 09:16 UTC, ArturFriesen requested changes

2022-02-07 11:48 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
>  		var boosterRulesDidUpdate: Bool = false
I think there is no tread-safety issue here, as these are local variables inside a function and not shared with anyone else, right? I think there is currently no scenario in which they could be read/written in parallel

2022-02-07 11:58 UTC, ArturFriesen approved these changes

2022-02-07 12:44 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Services/CCLService/CCLService.swift
>  		var boosterRulesDidUpdate: Bool = false
Good point we might add a lock to make sure it becomes thread save. The dispatch group used is just handy to collect the requests made.

2022-02-07 13:41 UTC, merged