Task/11693 unit tests for rapid pcr tests
corona-warn-app/cwa-app-ios pull request #4205
Opened 2022-02-11 09:10 UTC by 30mar

## Description
add unit tests for rapid PCR tests

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11693)

2022-02-11 09:30 UTC, KathrinLuecke approved these changes
UA approved

2022-02-14 13:06 UTC, nickguendling requested changes

2022-02-14 13:06 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/QRScanner/_tests_/CoronaTestsQRCodeParserTests.swift
> +		let antigenTestInformation = RapidTestQRCodeInformation.mock(hash: invalidHash)
```suggestion
		let rapidTestInformation = RapidTestQRCodeInformation.mock(hash: invalidHash)
```

Same for the ones below, just to keep the naming consistent

2022-02-15 12:11 UTC, naveeddotio approved these changes

2022-02-15 12:16 UTC, nickguendling approved these changes

2022-02-16 09:28 UTC, merged