Story/11356 support rapid pcr tests
corona-warn-app/cwa-app-ios pull request #4213
Opened 2022-02-14 10:59 UTC by 30mar

## Description
Add logic to support rapid PCR tests

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11356

2022-02-14 12:25 UTC, nickguendling approved these changes

2022-02-14 12:28 UTC, nickguendling requested changes
I tried to scan a rapid PCR test from the external camera but it didn't show the submission flow, it works for antigen tests

2022-02-14 14:23 UTC, nickguendling requested changes

2022-02-15 09:17 UTC, naveeddotio approved these changes

2022-02-15 12:15 UTC, nickguendling approved these changes

2022-02-16 11:58 UTC, merged