Task/11779 changes certificate overview screen
corona-warn-app/cwa-app-ios pull request #4217
Opened 2022-02-14 19:07 UTC by naveeddotio

## Description
Changes to health certificate overview screen 

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11779

2022-02-15 08:26 UTC, CV113 requested changes

2022-02-15 08:26 UTC, CV113 commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"HealthCertificate_Overview_EmptyDescription" = "Hier werden die gespeicherten digitalen Impfzertifikate, Genesenenzertifikate und Testzertifikate angezeigt.\n\nScannen Sie den QR-Code des Zertifikat
A hyphen is missing
 WRONG: QR-Code Scanners 
 RIGHT: QR-Code-Scanners

2022-02-15 10:18 UTC, CV113 approved these changes
UA approved

2022-02-15 16:46 UTC, KaiTeuber approved these changes

2022-02-16 12:45 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewModel.swift
> +			return healthCertifiedPersons.isEmpty ? 0 : 1
this logic will be replaced by task 11811
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11811

2022-02-16 14:43 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/Cells/__tests__/ChangeAdmissionScenarionCellModelTests.swift
> +
Yes

2022-02-16 14:58 UTC, pascal-brause approved these changes

2022-02-16 15:03 UTC, merged