Added quick actions for qr code scanner and certificates
corona-warn-app/cwa-app-ios pull request #4238
Opened 2022-02-18 08:47 UTC by ln-12

## Description
This PR is meant to complete https://github.com/corona-warn-app/cwa-app-android/pull/4685, so that both Android and iOS can get all four app shortcuts/quick actions. I followed the suggestions in https://github.com/corona-warn-app/cwa-app-android/pull/4642 to hopefully meet all requirements. If not, please let me know.

For now I only added german and english localization, the other languages need to be done.

## Link to Jira
[https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5414](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5414)

## Screenshots
![7A34CE80-6049-4C8F-9790-F191F0302B00](https://user-images.githubusercontent.com/36760115/154648320-c99ceb14-74e2-48de-8900-39bb642a5360.jpeg)

2022-02-18 09:31 UTC, CV113 approved these changes
UA approved

2022-03-02 14:18 UTC, marcussc requested changes

2022-03-02 15:17 UTC, 30mar requested changes
@ln-12  thanks alot for you effort, I tested the project locally and I've added some comments, feel free to reply to them if you need to clarify something. :)

2022-03-02 15:17 UTC, 30mar commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
> +		]
```suggestion
		var shortcutItems = [
			UIApplicationShortcutItem(type: QuickAction.diaryNewEntry.rawValue, localizedTitle: AppStrings.QuickActions.contactDiaryNewEntry, localizedSubtitle: nil, icon: UIApplicationShortcutIcon(templateImageName: "book.closed")),
			UIApplicationShortcutItem(type: QuickAction.showCertificates.rawValue, localizedTitle: AppStrings.QuickActions.showCertificates, localizedSubtitle: nil, icon: UIApplicationShortcutIcon(templateImageName: "Icons_Tabbar_Certificates"))
		]
```

2022-03-02 15:17 UTC, 30mar commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
>  			shortcutItems.append(
```suggestion
			shortcutItems.append(
				contentsOf: [
					UIApplicationShortcutItem(type: QuickAction.qrCodeScanner.rawValue, localizedTitle: AppStrings.QuickActions.qrCodeScanner, localizedSubtitle: nil, icon: UIApplicationShortcutIcon(templateImageName: "qrcode.viewfinder")),
					UIApplicationShortcutItem(type: QuickAction.eventCheckin.rawValue, localizedTitle: AppStrings.QuickActions.eventCheckin, localizedSubtitle: nil, icon: UIApplicationShortcutIcon(templateImageName: "Icons_Tabbar_Checkin"))
				]
			)
```

2022-03-02 15:17 UTC, 30mar commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
>  			)
```suggestion

```

2022-03-02 15:17 UTC, 30mar commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
> +
```suggestion
						// open qr code scanner for fast event checkin
			coordinator.checkinTabCoordinator?.showQRCodeScanner()

```

2022-03-02 15:18 UTC, ln-12 commented on src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
> +
Done

2022-03-02 15:26 UTC, ln-12 commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/AppDelegate+QuickActions.swift
> +		]
Hey, thanks for the suggestions. I added all of these.

2022-03-03 09:49 UTC, ln-12 commented
@marcussc That because of @30mar's comment above: https://github.com/corona-warn-app/cwa-app-ios/pull/4238#discussion_r817792932

Of course, I can remove it again, but you have to have the same opinion on what's needed...

2022-03-03 12:21 UTC, marcussc commented
@ln-12 @30mar so we had a short internal discussion and decided it makes more sense to not show the QR Code scanner on the "Check-ins anzeigen" Quickaction. It used to do this before we had the universal QRCodescanner. 
Sorry for the confusion that my have caused.

2022-03-03 12:48 UTC, ln-12 commented
@marcussc Nevermind, I changed it back :)

2022-03-03 12:53 UTC, marcussc commented
@ln-12 thank you. One last small thing, please move the "Check-ins anzeigen" to the third position. Then I don't see anything that stands in the way of merging your PR :)

2022-03-03 13:07 UTC, ln-12 commented
Alright, I reordered the actions.

2022-03-03 13:10 UTC, 30mar approved these changes

2022-03-03 13:11 UTC, marcussc approved these changes

2022-03-03 13:38 UTC, merged