Feature/fix certificate comparison
corona-warn-app/cwa-app-ios pull request #4243
Opened 2022-02-18 13:10 UTC by pascal-brause

## Description
Main fix 1: Compare after swipe to delete on one certificate if we need to delete more certificates because the person splits afterwards. 
Main fix 2: Replaces equatable compare between healthCertifiedPersons on their attributes by their reference.
Fixes then every occurrence of the identity operator between persons and use the equal operator.
Fixes also some tests where we cannot longer check between persons and instead we check now their properties.

2022-02-18 13:17 UTC, nickguendling requested changes

2022-02-18 14:11 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/HealthCertifiedPerson/HealthCertifiedPersonViewModel.swift
> +
Quickly fixed it myself 🤓

2022-02-18 14:55 UTC, nickguendling approved these changes

2022-02-21 09:04 UTC, ArturFriesen approved these changes

2022-02-21 09:05 UTC, merged