Feature/11784 UI test federal state configuration
corona-warn-app/cwa-app-ios pull request #4259
Opened 2022-02-23 16:13 UTC by naveeddotio

## Description
UI test to check if the flow works correctly

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11784

2022-02-24 14:34 UTC, nickguendling requested changes

2022-02-24 14:34 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Overview/HealthCertificateOverviewViewController.swift
> +		cell.accessibilityLabel = viewModel.changeAdmissionScenarioButtonText?.localized(cclService: cclService) ?? AppStrings.HealthCertificate.Overview.admissionScenarioButtonLabel
Why is this needed? Seemed to me like VoiceOver read the correct text before already

2022-02-24 14:34 UTC, nickguendling commented on src/xcode/ENA/ENAUITests/HealthCertificate/ENAUITests_13_CreateHealthCertificate.swift
> +	func test_screenshot_HealthCertificate_FederalState_Flow() throws {
```suggestion
	func test_HealthCertificate_FederalState_Flow() throws {
```

Seems like we don't take a screenshot

2022-02-24 15:59 UTC, 30mar approved these changes

2022-02-25 09:22 UTC, nickguendling approved these changes

2022-02-25 09:45 UTC, merged