Story/12045 feature switch changes - 11995 text changes based on feature switch
corona-warn-app/cwa-app-ios pull request #4269
Opened 2022-02-25 15:26 UTC by naveeddotio

## Description
- Changes for feature switch based on app config
- Text changes based on feature switch

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11995
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12045

## Screenshots
![Simulator Screen Shot - iPhone 12 - 2022-02-25 at 15 51 03](https://user-images.githubusercontent.com/77438487/155741547-49b2b799-6fd6-4315-a6ce-76250c5ac1ba.png)
![Simulator Screen Shot - iPhone 12 - 2022-02-25 at 15 51 16](https://user-images.githubusercontent.com/77438487/155741558-1cc9b3db-0019-46b3-b792-eaa707a22cb9.png)
![Simulator Screen Shot - iPhone 12 - 2022-02-25 at 15 57 44](https://user-images.githubusercontent.com/77438487/155741571-eee167e9-7c19-4d57-af37-533910a9d119.png)

2022-02-25 17:20 UTC, marcussc requested changes
Seems like the Text "Fügen Sie weitere Zertifikate über den QR-Code-
Scanner in der unteren Navigationsleiste hinzu" should have the same Alpha value as "Hier werden die gespeicherten digitalen Impfzertifikate, Genesenenzertifikate und Testzertifikate angezeigt" but in the Screenshots they seem to have different Alpha values.

2022-02-28 08:13 UTC, KathrinLuecke approved these changes
UA approved

2022-02-28 14:55 UTC, ArturFriesen approved these changes

2022-03-01 09:20 UTC, marcussc approved these changes

2022-03-01 09:20 UTC, merged