Feature/add loading screen
corona-warn-app/cwa-app-ios pull request #4306
Opened 2022-03-08 16:11 UTC by nickguendling

## Description

- Separates the setup of the health certificate service so it is executed after the app launch time window so the watch dog doesn't kill the app if the setup takes longer than 5 seconds.
- Introduces a loading screen that shows a loading indicator if the setup of the health certificate service takes longer than 3 seconds. (Necessary due to the new migration, especially on old devices with lots of certificates)
- Sets the wallet info to nil for persons merged during the migration so their wallet info is recalculated.
- Ensures that no certificate requests are executed during health certificate service setup.
- Shows summed up the amount of certificates for all persons in the dev menu.

## Video of loading screen
https://user-images.githubusercontent.com/1157991/157277399-3f7ed4ab-760c-4784-b676-e0b0ff9dc5a8.MP4

2022-03-08 16:24 UTC, pascal-brause approved these changes

2022-03-09 09:03 UTC, ArturFriesen requested changes

2022-03-09 13:06 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateRequestService.swift
> +		healthCertificateService.$isSetUp
I don't think that is possible, as this registration is synchronously on the main thread right from AppDelegate.init(). There shouldn't be a chance for the setup to finish, or even start, before the init() returns.

2022-03-09 14:02 UTC, ArturFriesen approved these changes

2022-03-09 14:45 UTC, merged