Story/11827 changes recovery certificates details
corona-warn-app/cwa-app-ios pull request #4314
Opened 2022-03-09 12:22 UTC by naveeddotio

## Description
Changes related to recovery certificates on various screens

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11827

## Screenshots
![WhatsApp Image 2022-03-09 at 13 19 33-2](https://user-images.githubusercontent.com/77438487/157440919-99232cc7-6d0b-40a5-9097-b29926defc27.jpeg)
![WhatsApp Image 2022-03-09 at 13 19 34](https://user-images.githubusercontent.com/77438487/157440965-518f57c6-00d9-4496-b730-2942e086064c.jpeg)
![WhatsApp Image 2022-03-09 at 13 19 34-2](https://user-images.githubusercontent.com/77438487/157440978-e8858f1c-4dfb-4296-9dec-2aa9677d894a.jpeg)
![WhatsApp Image 2022-03-09 at 13 19 33](https://user-images.githubusercontent.com/77438487/157441001-d810a731-a384-41b9-a809-c1ece9242388.jpeg)
![WhatsApp Image 2022-03-09 at 13 19 31](https://user-images.githubusercontent.com/77438487/157441021-720a9ef6-c3cd-4d2c-8288-a0bc8401ef2a.jpeg)
![WhatsApp Image 2022-03-09 at 13 19 32](https://user-images.githubusercontent.com/77438487/157441032-07364475-04de-4d9d-b6e3-2514ca7286dc.jpeg)

2022-03-09 12:54 UTC, CV113 approved these changes
UA approved

2022-03-10 14:11 UTC, ArturFriesen requested changes

2022-03-10 14:11 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/Models/Extensions/RecoveryEntry+Extension.swift
>  		return ISO8601DateFormatter.justLocalDateFormatter.date(from: certificateValidUntil)
Can 'localCertificateValidityStartDate' and 'localCertificateValidityEndDate' be removed from the extension?

2022-03-10 16:42 UTC, luisoos approved these changes

2022-03-11 09:11 UTC, ArturFriesen approved these changes

2022-03-11 13:41 UTC, merged

2022-03-11 18:12 UTC, Ein-Tim commented
@naveeddotio I have a question on the last picture you used in this PR. Is this actually going to happen? The text talks about vaccination certificates, however, the recovery certificate is the certificate to be updated. 

If this should not happen in productive environment: Ok, no problem.
If this is actually possible to happen in productive environment: I suggest to change the text.

Ping @thomasaugsten

2022-03-11 19:52 UTC, thomasaugsten commented
The last screenshot cannot happen at the moment in production. Because only 2/2 vaccination certificate can be replaced at the moment.