Add maxEncounterAgeInDays to days since install screen.
corona-warn-app/cwa-app-ios pull request #4332
Opened 2022-03-15 07:43 UTC by ArturFriesen

## Description
Add maxEncounterAgeInDays to days since install screen.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12123

2022-03-15 07:53 UTC, KathrinLuecke approved these changes
UA approved

2022-03-15 08:10 UTC, 30mar approved these changes

2022-03-15 10:52 UTC, KaiTeuber requested changes

2022-03-15 10:52 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/ENSetting/Cells/DaysSinceInstallTableViewCell.swift
> +	private var viewModel: DaysSinceInstallCellViewModel!
force unwrap, what about swiftlint?

2022-03-16 10:24 UTC, naveeddotio approved these changes

2022-03-16 12:49 UTC, merged