Fix/clean test names
corona-warn-app/cwa-app-ios pull request #4333
Opened 2022-03-15 09:21 UTC by ArturFriesen

## Description
Remove not needed name parts from UI-Tests.

2022-03-15 09:35 UTC, marcussc requested changes

2022-03-15 09:53 UTC, ArturFriesen commented on src/xcode/ENA/TestPlans/ContactJournalUITests.xctestplan
> +        "ENAUITests_ContactJournal\/testAddLocationToDate()",
I'm also wondering about that. The old names are still in the file but don't show up in the UI.

2022-03-15 09:55 UTC, ArturFriesen commented on src/xcode/ENA/TestPlans/ContactJournalUITests.xctestplan
> +        "ENAUITests_ContactJournal\/testAddLocationToDate()",
I think I need to remove them manually from the file content.

2022-03-16 13:00 UTC, naveeddotio commented on src/xcode/ENA/TestPlans/ContactJournalUITests.xctestplan
> +        "ENAUITests_ContactJournal\/testAddLocationToDate()",
It's a bug in Xcode.

2022-03-16 16:13 UTC, ArturFriesen commented on src/xcode/ENA/TestPlans/ContactJournalUITests.xctestplan
> +        "ENAUITests_ContactJournal\/test_screenshot_AddTwoPersonsTwoLocations()",
Do you mean ENAUITests target?

2022-03-17 09:12 UTC, marcussc commented on src/xcode/ENA/TestPlans/ContactJournalUITests.xctestplan
> +        "ENAUITests_ContactJournal\/test_screenshot_AddTwoPersonsTwoLocations()",
![Screenshot 2022-03-17 at 10 11 47](https://user-images.githubusercontent.com/10122052/158776307-f1707ad6-1867-415a-9c65-5953c298f6fe.png)
Whatever this is called? Target? Testtarget?

2022-04-08 08:11 UTC, closed without merging