Feature/12350 update old logic to check the blocklist
corona-warn-app/cwa-app-ios pull request #4359
Opened 2022-03-21 08:35 UTC by 30mar

## Description
update old logic to check the blocklist based on the list of blocked certificate refrences that we get from the CCL

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12350

2022-03-21 09:10 UTC, naveeddotio approved these changes

2022-03-21 12:27 UTC, nickguendling requested changes

2022-03-21 12:27 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/CCLService/__tests__/DCCWalletInfo+Fake.swift
> +		certificatesRevokedByInvalidationRules: [DCCCertificateContainer] = [.fake()]
```suggestion
		certificatesRevokedByInvalidationRules: [DCCCertificateContainer] = []
```
For fakes the default should usually be empty. The caller should not assume anything about the default parameters and set them if they are required for the test case.

2022-03-21 12:27 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/HealthCertificate/HealthCertificateService.swift
> +		if let invalidationRules = person.dccWalletInfo?.certificatesRevokedByInvalidationRules, healthCertificate.isBlocked(by: invalidationRules) {
If I would keep it in a separate function, I would probably move it to the person now, but I don't think it makes much sense to have this separate function anymore as it is just a `contains` call.

```suggestion
		if let revokedCertificates = person.dccWalletInfo?.certificatesRevokedByInvalidationRules, 
			revokedCertificates.contains(where: { $0.certificateRef.barcodeData == healthCertificate.base45 }) {
```

Unit tests (which still seem to be to do for this PR) will then have to be done with the service unit tests.

2022-03-24 18:12 UTC, nickguendling approved these changes

2022-03-25 03:57 UTC, merged