Feature/12219 testprocess family members/12303 user selection
corona-warn-app/cwa-app-ios pull request #4371
Opened 2022-03-22 14:05 UTC by naveeddotio

## Description
PR to add test owner selection screen

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12303

## Screenshots
![Simulator Screen Shot - iPhone 13 - 2022-03-22 at 15 05 11](https://user-images.githubusercontent.com/77438487/159499888-1aaf24e8-1862-4056-ba86-104e3a666a3e.png)

2022-03-22 14:18 UTC, CV113 approved these changes
UA approved

2022-03-23 16:55 UTC, KaiTeuber commented
I'm not sure if dark mode looks correct - I was wondering if it is as requested. The section tiles are not visible in the dark mode.

2022-03-23 16:57 UTC, naveeddotio commented
> I'm not sure if dark mode looks correct - I was wondering if it is as requested. The section tiles are not visible in the dark mode.

I will have a look

2022-03-24 11:31 UTC, KaiTeuber commented
Dynamic type is broken too

2022-03-24 11:37 UTC, KaiTeuber requested changes
Dark mode and dynamic type need a bit more work

2022-03-24 11:37 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestOwnerSelection/ExposureSubmissionTestOwnerSelectionViewController.swift
> +}
```suggestion
```
Move it over to the viewModel

2022-03-24 11:37 UTC, KaiTeuber commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestOwnerSelection/ExposureSubmissionTestOwnerSelectionViewModel.swift
> +
```suggestion
enum TestOwner {
	case user
	case familyMember
}
```

2022-03-24 13:09 UTC, KaiTeuber approved these changes

2022-03-24 13:37 UTC, naveeddotio commented
> Dark mode and dynamic type need a bit more work

Fixed. Thanks for looking into it.

2022-03-24 13:43 UTC, 30mar approved these changes

2022-03-24 14:28 UTC, merged