Feature/12219 testprocess family members/12340 create family member consent screen
corona-warn-app/cwa-app-ios pull request #4379
Opened 2022-03-23 16:42 UTC by KaiTeuber

## Description
Added new family test consent screen to enter name of family member. Included the screen to the flow into coordinator and added some simple unit tests.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12340

## Screenshots
![Simulator Screen Shot - iPhone 8 - 2022-03-23 at 17 41 45](https://user-images.githubusercontent.com/2675578/159751369-bec46a26-d5fc-4811-9721-c70f3d6ff6b4.png)
![Simulator Screen Shot - iPhone 8 - 2022-03-23 at 17 42 23](https://user-images.githubusercontent.com/2675578/159751374-b04f6b0e-6e3c-4c9a-853d-d59b1db4fc22.png)

2022-03-23 16:53 UTC, KathrinLuecke commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"HealthCertificate_FamilyMemberConsent_InputTitle" = "Name der Person, die geteste wurde:";
```suggestion
"HealthCertificate_FamilyMemberConsent_InputTitle" = "Name der Person, die getestet wurde:";
```

2022-03-23 16:54 UTC, KathrinLuecke requested changes
correct typo

2022-03-24 13:22 UTC, KathrinLuecke approved these changes
UA approved

2022-03-24 14:51 UTC, ArturFriesen approved these changes

2022-03-24 14:51 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/FamilyMemberConsent/FamilyNameTextFieldCell.swift
> +	@OpenCombine.Published private(set) var model: String?
```suggestion
	@OpenCombine.Published private(set) var name: String?
```

2022-03-24 15:17 UTC, naveeddotio approved these changes

2022-03-24 15:44 UTC, merged