Add resource for kid list.
corona-warn-app/cwa-app-ios pull request #4418
Opened 2022-04-04 10:35 UTC by ArturFriesen

## Description
Adds resource for kid list request.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12575

2022-04-04 11:55 UTC, pascal-brause requested changes

2022-04-04 11:55 UTC, pascal-brause commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/KIDListResource.swift
> +		case (400...409):
```suggestion
		case (400...499):
```

2022-04-04 11:55 UTC, pascal-brause commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/KIDListResource.swift
> +		case (509...509):
```suggestion
		case (500...599):
```

2022-04-04 14:27 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/KIDListResource.swift
> +		case (509...509):
Changed

2022-04-04 14:27 UTC, ArturFriesen commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/DCCRevocation/KIDList/KIDListResource.swift
> +		case (400...409):
changed

2022-04-05 11:49 UTC, pascal-brause approved these changes

2022-04-05 13:03 UTC, pascal-brause approved these changes
It's really easy work, but could you add the test for the unique identifier for the new resource?
And what about the unit tests itself?

2022-04-05 14:45 UTC, KaiTeuber approved these changes

2022-04-06 08:22 UTC, merged