Delete Ihr/ Ihres/ Ihnen
corona-warn-app/cwa-app-ios pull request #4433
Opened 2022-04-06 12:39 UTC by CV113

no "Ihr"/"Ihren" -> because its a family members certificate (please see also the figma screens COVID19_Master_2.18 – Figma)
--> https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12656

2022-04-06 12:59 UTC, KathrinLuecke commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> +"ExposureSubmissionResult_testPending" = "Das Testergebnis liegt noch nicht vor";
"Ihr" is correct here; there is an extra string for pending test results for family members

2022-04-06 12:59 UTC, KathrinLuecke commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
>  "ExposureSubmissionResult_familyMember_testPending" = "Ihr Testergebnis liegt noch nicht vor";
```suggestion
"ExposureSubmissionResult_familyMember_testPending" = "Das Testergebnis liegt noch nicht vor";
```

2022-04-06 13:03 UTC, KathrinLuecke requested changes
Maybe all strings should be duplicated to reflect wether it's a test for the owner of the smartphone or a family member. Currently only some are duplicated to differentiate between these cases.

2022-04-08 10:38 UTC, closed without merging

2022-04-08 10:38 UTC, CV113 commented
Closed
Changes for 2.22