Fix/12943 button weiter jumps back to ihre testverwaltung
corona-warn-app/cwa-app-ios pull request #4487
Opened 2022-04-27 10:34 UTC by 30mar

## Description
fix navigation bug by setting markAsSeen after we decide the first navigation choice and not before it.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12943

## Screenshots
https://user-images.githubusercontent.com/15270737/165498828-085043ac-14ed-42f0-aeff-321bd5bde7e6.mov

2022-04-27 10:49 UTC, naveeddotio approved these changes

2022-04-27 12:07 UTC, KaiTeuber requested changes

2022-04-28 05:26 UTC, 30mar commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +				viewModel.markScreenSeen()
@KaiTeuber updated 👍

2022-04-28 09:37 UTC, KaiTeuber approved these changes

2022-04-28 09:37 UTC, merged