Add new property to track test result change to invalid.
corona-warn-app/cwa-app-ios pull request #4575
Opened 2022-05-23 12:38 UTC by ArturFriesen

## Description
With this fix, the test result change from pending, positive or negative to invalid is considered and the red dot is shown.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12667

2022-05-24 12:13 UTC, nickguendling requested changes

2022-05-24 12:13 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/Services/CoronaTestService/FamilyMemberCoronaTestService.swift
> -					testResultWasShown: LaunchArguments.familyMemberTest.pcr.positiveTestResultWasShown.boolValue,
Do we use the launch arguments (this one and the one for antigen) anywhere? I think we should either replace them with new ones for the new property or remove them completely

2022-05-24 13:46 UTC, nickguendling approved these changes

2022-05-25 10:06 UTC, 30mar approved these changes

2022-05-25 10:37 UTC, merged