added missing icon and text
corona-warn-app/cwa-app-ios pull request #4580
Opened 2022-05-24 14:29 UTC by KaiTeuber

## Description
Added a missing section of text and icon in the tracelocation information screen

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11237

## Screenshots
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-05-24 at 16 26 54](https://user-images.githubusercontent.com/2675578/170060469-60b284b9-7ff2-451c-9a8b-ca995872798e.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-05-24 at 16 27 02](https://user-images.githubusercontent.com/2675578/170060484-a5d4d764-858a-41d1-a90b-eb8ac18eb1d9.png)

2022-05-24 15:32 UTC, marcussc approved these changes

2022-05-24 15:48 UTC, naveeddotio approved these changes

2022-05-25 07:17 UTC, nickguendling requested changes
Not sure if this should still go into 2.23 now, I don't think there will be another translation run

2022-05-25 07:25 UTC, CV113 approved these changes
UA approved

2022-05-25 08:12 UTC, nickguendling approved these changes

2022-05-25 09:50 UTC, merged