Story/13242/13284 tooltip on share button
corona-warn-app/cwa-app-ios pull request #4610
Opened 2022-06-09 09:38 UTC by flxschmidt

## Description
Shows a Tooltip over new Export-Certificates BarButton, when navigate to Certificates Overview.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13284

## Screenshots
<img width="640px" alt="Screen Shot 2022-06-09 at 11 36 23" src="https://user-images.githubusercontent.com/22373291/172816846-398b9c5f-db1c-49b4-b967-a156273cba4c.png">

2022-06-10 12:13 UTC, KathrinLuecke approved these changes
UA approved

2022-06-13 10:19 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Views/TooltipViewController.swift
> +	init(
Missing mark

2022-06-13 10:20 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Views/TooltipViewController.swift
> +
Missing Mark

2022-06-13 10:20 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Views/TooltipViewController.swift
> +
Missing mark, please move it below init, for reference please see other VCs

2022-06-13 10:21 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Views/TooltipViewModel.swift
> +	var title: String {
Missing Marks and please reorder

2022-06-13 10:22 UTC, naveeddotio requested changes
Looks good, only some small things.

2022-06-13 15:26 UTC, naveeddotio approved these changes

2022-06-13 18:47 UTC, merged