re-prioritize background tasks
corona-warn-app/cwa-app-ios pull request #4658
Opened 2022-07-07 08:11 UTC by 30mar

## Description
Re prioritize background tasks, we out now checking certificates validity before the other operations

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9440

2022-07-07 15:07 UTC, naveeddotio approved these changes

2022-07-08 09:13 UTC, nickguendling requested changes

2022-07-08 09:13 UTC, nickguendling commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/ENATaskExecutionDelegate.swift
> +						}
As these are all async tasks, the order in which they are triggered will have no impact on the priority. They are all started in parallel.

2022-07-12 11:34 UTC, flxschmidt approved these changes

2022-07-15 10:04 UTC, closed without merging