Feature/10318 refactor els submission
corona-warn-app/cwa-app-ios pull request #4728
Opened 2022-08-15 11:30 UTC by 30mar

## Description
Refactor ELS submission
Not included:

- 3 commented three unit tests
- OTP submission

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10320

2022-08-15 12:40 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/ELS LoggingService/__tests__/ELSServiceTests.swift
> +			client: ClientMock(), // might fail
Didn't get the comment

2022-08-15 12:50 UTC, naveeddotio commented on src/xcode/ENA/ENA.xcodeproj/project.pbxproj
> +				8FE68F9228A146CC003E86E1 /* SubmitELSResource.swift */,
Can you please rename this and the corresponding files to ELSSubmitResource to align with PPASubmitResource

2022-08-15 13:03 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/ELS/SubmitELSResource.swift
> +enum SubmitELSResourceError: Error {
```suggestion
enum ELSSubmitResourceError: Error {
```

2022-08-15 14:13 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/ELS/SubmitELSRecieveModel.swift
> +struct SubmitELSReceiveModel: Codable {
```suggestion
struct ELSSubmitReceiveModel: Codable {
```

2022-08-15 14:13 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/ELS/SubmitElSSendModel.swift
> +struct SubmitElSSendModel: Encodable {
```suggestion
struct ElSSubmitSendModel: Encodable {
```

2022-08-15 14:20 UTC, naveeddotio approved these changes

2022-08-16 11:02 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Services/ELS LoggingService/__tests__/ELSServiceTests.swift
> +	// TO DO Related to OPT refactoring part
Before we merge commented code, we could also disable the dedicated test(s).

2022-08-16 12:36 UTC, naveeddotio requested changes
Blocking until the submit els issue is resolved.

2022-08-17 12:16 UTC, naveeddotio approved these changes
Works as expected.

2022-08-17 12:29 UTC, flxschmidt approved these changes
LGTM!

2022-08-17 12:29 UTC, flxschmidt commented on src/xcode/ENA/TestPlans/AllTests.xctestplan
> +        "ELSServiceTests\/testGIVEN_ELSService_WHEN_UploadIsTriggered_THEN_ServerErrorIsReturned()",
👍

2022-08-17 12:49 UTC, merged