Fix/11123 Add hyphenation also to My QR Codes and My Checkins
corona-warn-app/cwa-app-ios pull request #4863
Opened 2022-10-25 13:22 UTC by flxschmidt

## Description
Add hyphenation also to My QR Codes and My Checkins

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11123

## Screenshots
<img width="66%" alt="Screen Shot 2022-10-25 at 15 21 23" src="https://user-images.githubusercontent.com/22373291/197784439-602f89ae-e431-4a57-b84c-4bfb3a0f6fe9.png">

2022-10-25 13:45 UTC, puneetmahali1 approved these changes

2022-10-25 14:21 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Extensions/String+Attributed.swift
> +	func withHyhenationStyle(factor: Float = 0.8) -> NSAttributedString {
you meant Hyphenation?

```suggestion
	func withHyphenationStyle(factor: Float = 0.8) -> NSAttributedString {
```

2022-10-26 09:57 UTC, naveeddotio requested changes
Typo

2022-10-26 11:26 UTC, puneetmahali1 commented on src/xcode/ENA/ENA/Source/Extensions/String+Attributed.swift
> +	func withHyhenationStyle(factor: Float = 0.8) -> NSAttributedString {
typo fixed

2022-10-26 12:33 UTC, naveeddotio approved these changes

2022-10-26 12:33 UTC, merged