Fix/7429: Fehlerberichte ID History: IDs are ordered with oldest entry on top and newest entry to focus on at the bottom
corona-warn-app/cwa-app-ios pull request #4868
Opened 2022-10-28 14:12 UTC by flxschmidt

## Description
Fixx sorted order by descending ordered items.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7429

## Screenshots
<img width="66%" alt="Screen Shot 2022-10-28 at 16 09 49" src="https://user-images.githubusercontent.com/22373291/198636168-a64dc297-84bb-4a3c-b952-8f55e55ae35a.png">

2022-10-28 16:25 UTC, puneetmahali1 approved these changes

2022-11-02 09:07 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
> +	/// - Parameter sort: Wether the sort order is ascending, or descending
```suggestion
	/// - Parameter sort: Whether the sort order is ascending, or descending
```

2022-11-02 09:08 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
> +	/// - Returns: Returns the receipts in the specific order
```suggestion
	/// - Returns: Returns the receipts based on sortOrder
```

2022-11-02 09:09 UTC, naveeddotio requested changes
Small things :)

2022-11-03 15:12 UTC, naveeddotio approved these changes

2022-11-03 15:46 UTC, merged