Admin/SPM packages latest versions
corona-warn-app/cwa-app-ios pull request #4915
Opened 2022-12-06 10:16 UTC by flxschmidt

## Description
SPM Update to latest package versions.

## Screenshots

<img width="507" alt="Screenshot 2022-12-06 at 11 14 46" src="https://user-images.githubusercontent.com/22373291/205883451-e913a5d6-e04b-444a-ad9c-1149affcd373.png">

2022-12-06 10:33 UTC, puneetmahali1 approved these changes

2022-12-06 12:38 UTC, naveeddotio requested changes
We can not update the package file without having rigorous testing and checking if there are any side effects especially when it comes to FMDB

2022-12-20 12:53 UTC, 30mar approved these changes

2022-12-20 15:17 UTC, naveeddotio approved these changes

2022-12-20 15:45 UTC, merged