fix/7479 Add missing padding above the header image
corona-warn-app/cwa-app-ios pull request #4916
Opened 2022-12-06 14:50 UTC by puneetmahali1

## Description
Add missing padding above the header image on RAT Profile info screen

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7479

## Screenshots
<img width="636" alt="Padding 7479" src="https://user-images.githubusercontent.com/72390277/205944102-ac890375-0bd4-4d5a-b06f-f00f4b89950d.png">

2022-12-07 12:53 UTC, flxschmidt approved these changes
LGTM :)

2022-12-07 12:53 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewModel.swift
> +					.space(height: 15)
indent

2022-12-07 12:53 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateInfoViewModel.swift
> +					.space(height: 15)
indent

2022-12-07 12:55 UTC, puneetmahali1 commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/View/Controller/TestCertificate/ExposureSubmissionTestCertificateViewModel.swift
> +					.space(height: 15)
It's fine on Xcode.

2022-12-07 12:55 UTC, puneetmahali1 commented on src/xcode/ENA/ENA/Source/Scenes/HealthCertificates/Consent/HealthCertificateInfoViewModel.swift
> +					.space(height: 15)
This is also fine on Xcode.

2022-12-13 08:50 UTC, 30mar requested changes
This light gray line looks strange to me, im not sure if they updated the designs in figma or what, can you please provide the figma link so we can compare ?

2022-12-13 13:13 UTC, puneetmahali1 commented
> 
Actually, seems like there is a header space in iOS 12.5 and the bug assuming same in above iOS 12.5 too but let me check the figma designs with the colleagues.

2022-12-20 15:27 UTC, closed without merging