SRS Options: Reset all SRS State Values
corona-warn-app/cwa-app-ios pull request #4918
Opened 2022-12-06 16:03 UTC by flxschmidt

## Description
SRS Options: Reset all SRS State Values
See https://github.com/corona-warn-app/cwa-app-tech-spec/pull/186/commits/ffdd7b9d2b96f9e0e3a85fae559420727fbf5a17

## Screenshots
<img width="66%" alt="Screenshot 2022-12-06 at 17 01 45" src="https://user-images.githubusercontent.com/22373291/205961669-41626c1b-8533-4b3b-aef9-a3718552386d.png">

2022-12-06 16:17 UTC, puneetmahali1 approved these changes
👍

2022-12-06 18:45 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Developer Menu/DMSRSPrechecks/DMSRSOptionsViewModel.swift
> +					store.mostRecentKeySubmissionDate = nil
Shouldn't it be expiration date?

2022-12-06 18:46 UTC, naveeddotio requested changes
Please check my comment

2022-12-07 09:47 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Developer Menu/DMSRSPrechecks/DMSRSOptionsViewModel.swift
> +					store.mostRecentKeySubmissionDate = nil
Yes, that the next line ;)

2022-12-07 10:46 UTC, naveeddotio approved these changes

2022-12-07 12:37 UTC, merged