Task/14355 add submission unit tests
corona-warn-app/cwa-app-ios pull request #4933
Opened 2022-12-13 08:41 UTC by 30mar

## Description
Add submission unit tests

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14355

2022-12-14 11:38 UTC, flxschmidt approved these changes
LGTM! 🍒

2022-12-14 13:48 UTC, puneetmahali1 approved these changes
👍

2022-12-14 15:33 UTC, naveeddotio requested changes

2022-12-14 15:33 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/__tests__/OTPAuthorizationForSRSResourceTests.swift
> +	func testGIVEN_AuthorizeOTP_WHEN_NoNetworkConnection_THEN_NetworkErrorReturned() {
Can you please add a test case for .deviceBlocked?

2022-12-14 15:41 UTC, naveeddotio requested changes
Please see comments

2022-12-14 15:41 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/__tests__/OTPAuthorizationForSRSResourceTests.swift
> +				XCTAssertEqual(customError, .otherServerError)
the name of the test suggest that it should return internalServerError but in the end we are equating to otherServerError, both of them are different errors if we look into the enum types, am I missing something here?

2022-12-14 15:42 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/HTTPClient/Resources/OTPAuthorizationForSRS/__tests__/OTPAuthorizationForSRSResourceTests.swift
> +	func testGIVEN_AuthorizeOTP_WHEN_NoNetworkConnection_THEN_NetworkErrorReturned() {
Please refer to this PR: https://github.com/corona-warn-app/cwa-app-ios/pull/4928/files

2022-12-15 09:20 UTC, naveeddotio approved these changes

2022-12-15 10:31 UTC, merged