Fix SRS flow issues
corona-warn-app/cwa-app-ios pull request #4938
Opened 2022-12-14 15:20 UTC by naveeddotio

## Description
Fixing the missing confirmation alert for SRS submission

2022-12-14 15:23 UTC, puneetmahali1 approved these changes

2022-12-15 07:41 UTC, flxschmidt requested changes

2022-12-15 07:41 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/ExposureSubmission/ExposureSubmissionCoordinator.swift
> +					self.model.shouldShowSymptomsOnsetScreen ? self.showSymptomsOnsetScreen() : self.showSRSFlowConsentAlert(for: .confirmWarnOthers(on: exposureSubmissionSymptomsViewController), isLoading: isLoadi
```suggestion
					self.model.shouldShowSymptomsOnsetScreen
						? self.showSymptomsOnsetScreen()
						: self.showSRSFlowConsentAlert(
							for: .confirmWarnOthers(on: exposureSubmissionSymptomsViewController),
							isLoading: isLoading
						)
```

2022-12-15 09:14 UTC, flxschmidt approved these changes

2022-12-15 09:17 UTC, merged