Task/14824 new thank you tile on home screen
corona-warn-app/cwa-app-ios pull request #5055
Opened 2023-02-21 09:15 UTC by 30mar

## Description
add new Thank you tile as per techspecs

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14824

## Screenshots

Uploading RPReplay_Final1685778128.mov…

Uploading RPReplay_Final1685778128.mov…

2023-02-21 09:18 UTC, Ein-Tim commented
The file upload for the videos wasn't successful, unfortunately. Maybe you could try again? (:

2023-02-21 10:51 UTC, 30mar commented
@Ein-Tim thanks for the heads up, i re uploaded the video

2023-02-21 14:18 UTC, flxschmidt requested changes
Nice code, clean. Minor hints. :)

2023-02-21 14:18 UTC, flxschmidt commented on src/xcode/ENA/ENA.xcodeproj/project.pbxproj
> +		8F43E69029A32A890047C21F /* EndOfLifeThankYouCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8F43E68E29A32A890047C21F /* EndOfLifeThankYouCell.swift */; };
Funny name 😂

2023-02-21 14:18 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCell.swift
> +		}
```suggestion
illustrationImageView.isHidden = traitCollection.preferredContentSizeCategory >= .accessibilityLarge
```

2023-02-21 14:18 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/Home/Cells/EndOfLifeThankYou/EndOfLifeThankYouCellViewModel.swift
> +	// TODO get the xx value in figma
```suggestion
	// to.do get the xx value in figma
```

2023-02-21 14:18 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
> +				let isHibernationState = CWAHibernationProvider.shared.isHibernationState
Please pass the dependency in the constructor

```swift
init(cwaHibernationProvider: CWAHibernationProvider = CWAHibernationProvider.shared) { ... }
```

2023-02-21 14:21 UTC, 30mar commented on src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
> +				let isHibernationState = CWAHibernationProvider.shared.isHibernationState
But it is a global variable why do we need to inject it?

2023-02-21 14:23 UTC, 30mar commented on src/xcode/ENA/ENA.xcodeproj/project.pbxproj
> +		8F43E69029A32A890047C21F /* EndOfLifeThankYouCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8F43E68E29A32A890047C21F /* EndOfLifeThankYouCell.swift */; };
we had another thankyou screen a year ago, and we also have  another endoflife tile "for the notice" so im trying to be more specific 😃  but do you have a better suggestion ?

2023-02-21 14:23 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
> +				let isHibernationState = CWAHibernationProvider.shared.isHibernationState
Cause of a clean pattern style. In this way, you could also write a unit test and give a mocked version into it. Or a version with a mocked store into it. Thatswhy I write a second constructor for the singleton, that can take a mocked store. ;)

2023-02-21 15:34 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Scenes/Home/HomeTableViewController.swift
> +				let isHibernationState = CWAHibernationProvider.shared.isHibernationState
As discussed, you can keep the singleton instance getter, without dependency injection as long you don't write a specific unit test with a mocked storage instance.

2023-02-22 07:22 UTC, KathrinLuecke approved these changes
UA approved

2023-02-23 12:47 UTC, flxschmidt approved these changes
LGTM

2023-02-27 10:04 UTC, naveeddotio approved these changes

2023-02-27 10:43 UTC, puneetmahali1 approved these changes

2023-02-28 15:05 UTC, merged