Task/14817 Adapt Changes to Certificates
corona-warn-app/cwa-app-ios pull request #5058
Opened 2023-02-21 11:52 UTC by puneetmahali1

## Description
Ramp Down Changes for the Certificates.
- Proof of status tile hidden
- Proof of status tile hidden
- "Check Validity for Travel" button hidden
- Re-issuing of certificates shall be hidden

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14817

## Screenshots
https://user-images.githubusercontent.com/72390277/220337394-a5535180-9ae3-446d-a02b-f9359d463869.MP4

2023-02-21 15:32 UTC, naveeddotio requested changes
See comment

2023-02-21 15:32 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
> +			isPrimaryButtonHidden = CWAHibernationProvider.shared.isHibernationState
Missing if check here

2023-02-21 17:10 UTC, puneetmahali1 commented on src/xcode/ENA/ENA/Source/Scenes/FooterViewController/FooterViewModel.swift
> +			isPrimaryButtonHidden = CWAHibernationProvider.shared.isHibernationState
Added

2023-02-24 09:21 UTC, naveeddotio approved these changes

2023-02-27 09:36 UTC, naveeddotio requested changes
Tests are missing

2023-03-03 11:02 UTC, flxschmidt approved these changes

2023-03-03 11:16 UTC, 30mar approved these changes

2023-03-03 12:08 UTC, merged