Task/14815 Adapt changes to TabBar
corona-warn-app/cwa-app-ios pull request #5059
Opened 2023-02-21 15:28 UTC by flxschmidt

## Description
Hide **QR Scanner** and **Check-In** in TabBar when Hibernation.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14815

## Screenshots
<img width="66%" alt="Screenshot 2023-02-21 at 16 26 36" src="https://user-images.githubusercontent.com/22373291/220387208-410236fe-683c-4551-8242-cca30b2d8abf.png">

2023-02-22 11:25 UTC, puneetmahali1 approved these changes

2023-02-23 04:10 UTC, 30mar approved these changes

2023-02-27 09:35 UTC, naveeddotio commented
@flxschmidt do we have unit tests for tab bar buttons? I think they also need refactoring.

2023-02-27 09:36 UTC, naveeddotio requested changes
@flxschmidt do we have unit tests for tab bar buttons? I think they also need refactoring.

2023-02-27 10:26 UTC, naveeddotio approved these changes

2023-02-27 10:27 UTC, flxschmidt commented
> @flxschmidt do we have unit tests for tab bar buttons? I think they also need refactoring.

At the moment we have no existing test class for `RootCoordinator.swift` where `TabBar` is also a `private let`. Nothing from that class is tested.

2023-02-27 10:33 UTC, merged