Task/14818 adapt changes to notifications
corona-warn-app/cwa-app-ios pull request #5060
Opened 2023-02-23 04:30 UTC by 30mar

## Description
Adapt changes to notifications

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14818

2023-02-27 10:20 UTC, flxschmidt approved these changes
LGTM

2023-02-28 09:14 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/DeadmanNotification/DeadmanNotificationManager.swift
> +		if !CWAHibernationProvider.shared.isHibernationState {
Instead of this, I would prefer to have a check on the function itself. Simply don't call it if it is in hibernation mode.

2023-02-28 09:15 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Scenes/Events/Store/EventCheckoutService.swift
> +		if !CWAHibernationProvider.shared.isHibernationState {
I would prefer to have a check on function level.

2023-02-28 09:18 UTC, naveeddotio requested changes
We do some stuff in applicationWillEnterForeground for the notifications as far as I remember. Also, please place the checks while calling the functions.

2023-03-02 12:13 UTC, naveeddotio approved these changes

2023-03-16 12:56 UTC, merged