Task/14820 adapt changes to ppa submission
corona-warn-app/cwa-app-ios pull request #5064
Opened 2023-02-27 18:04 UTC by flxschmidt

## Description
If the app is in hibernation state, the PPA submission shall be aborted.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14820

2023-02-28 09:05 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
> +			if strongSelf.cwaHibernationProvider.isHibernationState {
Please move the lines to the beginning of the function. We don't need to wait for the app configuration and all the code above.

2023-02-28 09:06 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
> +				XCTFail("Test should not success")
```suggestion
				XCTFail("Test should not succeed")
```

2023-02-28 09:06 UTC, naveeddotio requested changes
See comments

2023-02-28 12:08 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/PPAnalyticsSubmitter.swift
> +			if strongSelf.cwaHibernationProvider.isHibernationState {
done

2023-02-28 12:08 UTC, flxschmidt commented on src/xcode/ENA/ENA/Source/Services/PPAnalyticsSubmitter/__tests__/PPAnalyticsSubmitterTests.swift
> +				XCTFail("Test should not success")
changed

2023-03-01 10:30 UTC, 30mar approved these changes

2023-03-02 12:08 UTC, naveeddotio approved these changes
❤️

2023-03-06 14:17 UTC, merged