Task/14823 adapt changes to error logging
corona-warn-app/cwa-app-ios pull request #5065
Opened 2023-02-28 17:26 UTC by flxschmidt

## Description
Stop and delete error logs when app call `didFinishLaunchingWithOptions` and hibernation state is given. Prevent to submit error logs in `ELSService`.

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14823

2023-03-02 13:14 UTC, naveeddotio commented on src/xcode/ENA/ENA/Source/Services/ELS LoggingService/ELSService.swift
> +
Please check the logic while calling the function

2023-03-02 13:15 UTC, naveeddotio requested changes
Please check comments

2023-03-02 13:38 UTC, naveeddotio approved these changes

2023-03-03 08:53 UTC, 30mar approved these changes

2023-03-03 08:58 UTC, merged