Task/14821 Adapt changes to QR code scanning and deep links
corona-warn-app/cwa-app-ios pull request #5066
Opened 2023-02-28 21:28 UTC by puneetmahali1

## Description
In hibernation state scanning QR codes will redirect to the home page of the app

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14821

## Screenshots
https://user-images.githubusercontent.com/72390277/221984012-231e9581-dccf-4d2d-8248-ad5233eab9cf.MP4

2023-03-03 08:59 UTC, flxschmidt approved these changes

2023-03-06 13:48 UTC, 30mar approved these changes

2023-03-06 13:54 UTC, 30mar requested changes

2023-03-06 13:54 UTC, 30mar commented on src/xcode/ENA/ENA/Source/AppDelegate & Globals/Route.swift
> +// swiftlint:disable function_body_length
```suggestion
```

2023-03-06 15:26 UTC, merged