Feature/14956 Adapt privacy notice for Release 3.2
corona-warn-app/cwa-app-ios pull request #5109
Opened 2023-03-21 15:05 UTC by flxschmidt

## Description
Adapt privacy notice for Release 3.2:

- DE
- EN
- TR
- PL (english version)
- RO (english version)
- BGR (english version)

## Link to Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14956

## Screenshots
<img width="33%" src="https://user-images.githubusercontent.com/22373291/226648417-04587974-ac1a-4c1a-b121-f8aa53334ea1.png" />
<img width="33%" src="https://user-images.githubusercontent.com/22373291/226648448-57f946c4-8e14-4110-8887-f55c38855cf2.png" />
<img width="33%" src="https://user-images.githubusercontent.com/22373291/226648458-87496417-fd03-4553-96ff-81744a04c214.png" />

2023-03-21 15:10 UTC, 30mar approved these changes

2023-03-21 15:34 UTC, OLVI5 approved these changes

2023-03-21 19:36 UTC, Ein-Tim requested changes
Attention! The version number is wrong!

2023-03-21 19:36 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/privacy-policy.html
> +			Version 3.20 (gültig bis 30.04.2023)
```suggestion
			Version 3.2.0 (gültig bis 30.04.2023)
```

2023-03-21 19:36 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/bg.lproj/privacy-policy.html
> +			Version 3.20 (valid until 30 April 2023)
```suggestion
			Version 3.2.0 (valid until 30 April 2023)

```

2023-03-21 19:36 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/en.lproj/privacy-policy.html
> +			Version 3.20 (valid until 30 April 2023)
```suggestion
			Version 3.2.0 (valid until 30 April 2023)

```

2023-03-21 19:36 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/pl.lproj/privacy-policy.html
> +			Version 3.20 (valid until 30 April 2023)
```suggestion
			Version 3.2.0 (valid until 30 April 2023)

```

2023-03-21 19:36 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/ro.lproj/privacy-policy.html
> +			Version 3.20 (valid until 30 April 2023)
```suggestion
			Version 3.2.0 (valid until 30 April 2023)

```

2023-03-21 19:36 UTC, Ein-Tim commented on src/xcode/ENA/ENA/Resources/Localization/tr.lproj/privacy-policy.html
> +			Sürüm 3.20 (30.04.2023 tarihine kadar geçerlidir)
```suggestion
			Sürüm 3.2.0 (30.04.2023 tarihine kadar geçerlidir)
```

2023-03-22 09:09 UTC, merged

2023-03-22 10:36 UTC, Ein-Tim commented
@flxschmidt Did you have a look at my review?