[Feature] ENAButton activity indicator for submission flow
corona-warn-app/cwa-app-ios pull request #753
Opened 2020-06-23 11:17 UTC by EisvogelSAP

This PR implements an activity indicator for the `ENAButton`. The indicator is applied to the submission flow loading states.

2020-06-23 13:27 UTC, melloskitten commented
When clicking on the "Aktualisieren" button in the pending Test Result screen, the activity indicator slides in from the left into the button. Is this intended behavior? it seems quite odd.

2020-06-23 13:30 UTC, melloskitten requested changes
Please look at my comment above :)

2020-06-25 08:21 UTC, melloskitten approved these changes

2020-06-25 10:37 UTC, inf2381 approved these changes

2020-06-25 10:49 UTC, merged