Translation Changes in DE & EN
corona-warn-app/cwa-app-ios pull request #786
Opened 2020-06-26 09:16 UTC by kaluju

2020-06-26 09:18 UTC, inf2381 approved these changes

2020-06-29 06:46 UTC, steins-code commented on src/xcode/ENA/ENA/Resources/Localization/de.lproj/Localizable.strings
> -"InviteFriends_ShareUrl" = "https://www.corona-warn-app.de";
This change is wrong

2020-06-29 06:46 UTC, steins-code commented on src/xcode/ENA/ENA/Resources/Localization/en.lproj/Localizable.strings
> +"safari_corona_website" = "https://www.bundesregierung.de/corona-warn-app-faq";
wrong change

2020-06-29 06:47 UTC, steins-code requested changes
2 wrong changes

2020-06-29 06:55 UTC, steins-code approved these changes

2020-06-29 07:20 UTC, merged