brought hourly fetching back
corona-warn-app/cwa-app-ios pull request #929
Opened 2020-07-21 11:44 UTC by ChristianKienle

## Checklist

* [ ] This PR does not change text that hasn't been signed off with the RKI. Have a look at the pinned issue [440](https://github.com/corona-warn-app/cwa-app-ios/issues)
* [ ] Test your changes as thoroughly as possible before you commit them. Preferably, automate your test by unit/integration tests.
* [ ] If this PR comes from a fork, please [Allow edits from maintainers](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)
* [ ] Set a speaking title. Format: {task_name} (closes #{issue_number}). For example: Use logger (closes # 41)
* [ ] [Link your Pull Request to an issue](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) - Pull Requests that are not linked to an issue with you as an assignee will be closed.
* [ ] Create Work In Progress [WIP] pull requests only if you need clarification or an explicit review before you can continue your work item.
* [ ] Make sure that your PR is not introducing _unnecessary_ reformatting (e.g., introduced by on-save hooks in your IDE)

## Description

2020-07-22 08:08 UTC, ChristianKienle commented on src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionExecutor.swift
> -	func allPackages(for day: String, onlyHours: Bool) -> [SAPDownloadedPackage] {
Just moved to where it belongs and removed `private` modifier so that it can be tested with our current structure.

2020-07-22 08:09 UTC, ChristianKienle commented on src/xcode/ENA/ENA/Source/Services/Exposure Transaction/ExposureDetectionDelegate.swift
> +struct DaysAndHours {
Made this a struct for better usability. (see below)

2020-07-22 08:09 UTC, ChristianKienle commented on src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/DownloadedPackagesStore.swift
> +extension DownloadedPackagesStore {
this code is not new just copy and pasted from someplace else to here.

2020-07-22 17:10 UTC, AdnanZiSAP commented
Tests project is failing to build it seems.

2020-07-22 17:11 UTC, AdnanZiSAP requested changes
Tests project is failing to build it seems.

2020-07-22 17:13 UTC, AdnanZiSAP commented
The code looks fine to me.

2020-07-23 08:19 UTC, ChristianKienle commented on src/xcode/ENA/ENA/Source/Services/DownloadedPackagesStore/DownloadedPackagesStore.swift
> +			packages.append(contentsOf: Array(allHoursForToday.prefix(3)))
this code is not new. just copy and pasted from another place to here. But it is fixed to three hours as per request by CS.

2020-07-23 08:40 UTC, haosap commented
> Tests project is failing to build it seems.

Hi @ChristianKienle ,
Test fails at `availableDaysAndHours: DaysAndHours = ([], []),`

2020-07-23 08:41 UTC, haosap requested changes
Please fix the test:
`availableDaysAndHours: DaysAndHours = ([], []),`

2020-07-23 09:37 UTC, AdnanZiSAP commented
@ChristianKienle Now a test fails :) 

"XCTAssertEqual failed: ("Optional([23])") is not equal to ("Optional([])")

        ENA/ENA/Source/Services/Exposure
        Transaction/__tests__/ExposureDetectionExecutorTests.swift:43"

2020-07-23 15:01 UTC, AdnanZiSAP approved these changes

2020-08-03 11:32 UTC, haosap approved these changes

2020-08-03 11:33 UTC, haosap commented
Hi @ChristianKienle ,
I approve it. Please merge it.
Thanks.

2020-08-04 12:02 UTC, merged